[package]
name = "swissarmyhammer-issues"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Issue management and tracking system for SwissArmyHammer"

[dependencies]
# Workspace dependencies
swissarmyhammer-common = { path = "../swissarmyhammer-common" }
swissarmyhammer-git = { path = "../swissarmyhammer-git" }
swissarmyhammer-issues-config = { path = "../swissarmyhammer-issues-config" }

# Core async and serialization
tokio = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }

# Utility and system
chrono = { workspace = true }
ulid = { workspace = true }
tracing = { workspace = true }

# JSON Schema for MCP interface
schemars = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio-test = "0.4"
git2 = { workspace = true }