[book]
title = "SwissArmyHammer Tools"
authors = ["SwissArmyHammer Contributors"]
description = "MCP server and tools for AI-powered development workflows"
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/swissarmyhammer/swissarmyhammer-tools"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/swissarmyhammer/swissarmyhammer-tools/edit/main/doc/{path}"

[output.html.fold]
enable = true
level = 1

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
