use std::env;
use std::fmt::Write;
use std::fs;
use std::path::Path;

fn main() {
    // Tell Cargo to re-run this build script if the rules directory changes
    println!("cargo:rerun-if-changed=../builtin/rules");

    let out_dir = env::var("OUT_DIR").unwrap();

    // Generate builtin rules
    generate_builtin_rules(&out_dir);
}

fn generate_builtin_rules(out_dir: &str) {
    let dest_path = Path::new(&out_dir).join("builtin_rules.rs");

    // Get the manifest directory (where Cargo.toml is located)
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let builtin_dir = Path::new(&manifest_dir).join("../builtin/rules");

    let mut code = String::new();
    code.push_str("// Auto-generated builtin rules - do not edit manually\n");
    code.push_str("// Generated by build.rs from builtin/rules directory\n\n");
    code.push_str("/// Get all built-in rules as a vector of (name, content) tuples\n");
    code.push_str("pub fn get_builtin_rules() -> Vec<(&'static str, &'static str)> {\n");
    code.push_str("    vec![\n");

    if builtin_dir.exists() {
        collect_rules(&builtin_dir, "", &mut code);
    }

    code.push_str("    ]\n");
    code.push_str("}\n");

    fs::write(&dest_path, code).unwrap();
}

fn collect_rules(dir: &Path, prefix: &str, code: &mut String) {
    if let Ok(entries) = fs::read_dir(dir) {
        let mut entries: Vec<_> = entries.collect();
        entries.sort_by_key(|entry| entry.as_ref().unwrap().path());

        for entry in entries.into_iter().flatten() {
            let path = entry.path();
            let name = path.file_name().unwrap().to_string_lossy();

            if path.is_dir() {
                // Recursively collect from subdirectories, including _partials
                let new_prefix = if prefix.is_empty() {
                    name.to_string()
                } else {
                    format!("{prefix}/{name}")
                };
                collect_rules(&path, &new_prefix, code);
            } else if name.ends_with(".md") || name.ends_with(".liquid") {
                // Generate the rule name
                let rule_name = if prefix.is_empty() {
                    name.strip_suffix(".md")
                        .or_else(|| name.strip_suffix(".liquid"))
                        .unwrap_or(&name)
                        .to_string()
                } else {
                    format!(
                        "{}/{}",
                        prefix,
                        name.strip_suffix(".md")
                            .or_else(|| name.strip_suffix(".liquid"))
                            .unwrap_or(&name)
                    )
                };

                // Read the file content at build time and embed it as a string literal
                if let Ok(content) = fs::read_to_string(&path) {
                    writeln!(code, "        (\"{rule_name}\", r#\"{content}\"#),").unwrap();
                }
            }
        }
    }
}
