- id: app.quit
  name: Quit
  keys:
    cua: Mod+Q
    vim: ":q"
  menu:
    path: [App]
    group: 2
    order: 0

- id: app.undo
  name: Undo
  undoable: false
  keys:
    cua: Mod+Z
    vim: u

- id: app.redo
  name: Redo
  undoable: false
  keys:
    cua: Mod+Shift+Z
    vim: Ctrl+R
