- id: settings.keymap.vim
  name: Vim Keybindings
  menu:
    path: [App, Settings]
    group: 0
    order: 1
    radio_group: keymap

- id: settings.keymap.cua
  name: Standard Keybindings
  menu:
    path: [App, Settings]
    group: 0
    order: 0
    radio_group: keymap

- id: settings.keymap.emacs
  name: Emacs Keybindings
  menu:
    path: [App, Settings]
    group: 0
    order: 2
    radio_group: keymap

- id: app.resetWindows
  name: Reset Windows
  menu:
    path: [App, Settings]
    group: 1
    order: 0
