//! Acceptance tests for the shipped `complexity-go` tool rule.
//!
//! Each test drives the SHIPPED script over a probe Go tree and reads what
//! the real gocognit reported.
//!
//! One module stands for each language of the family, because one file for
//! the whole family runs past the byte cap a review prompt holds.

use super::*;

/// A Go function whose innermost block stands 6 levels deep. gocognit adds
/// one for a block and one more for each level that block stands under, so
/// the cognitive complexity is 21 against the gate of 15.
const GO_COMPLEXITY_UNREAD_SOURCE: &str = r#"package probe

// Branch narrows a value, one nested block for each test.
func Branch(value int) int {
    if value > 0 {
        if value > 0 {
            if value > 0 {
                if value > 0 {
                    if value > 0 {
                        if value > 0 {
                            value--
                        }
                    }
                }
            }
        }
    }
    return value
}
"#;

/// Every Go file staged in the probe repository the complexity script is
/// given none of.
const GO_COMPLEXITY_UNREAD_FILES: &[(&str, &str)] = &[
    ("top.go", GO_COMPLEXITY_UNREAD_SOURCE),
    ("deep/nested/other.go", GO_COMPLEXITY_UNREAD_SOURCE),
];

/// Each finding the Go complexity script reports over the two files it is
/// given, as `path:line`.
const GO_COMPLEXITY_READ_FINDINGS: &[&str] = &["deep/nested/other.go:4", "top.go:4"];

/// The `complexity-go` probe over a run that is given no file.
const GO_COMPLEXITY_EMPTY_RUN_PROBE: ShippedEmptyRun = ShippedEmptyRun {
    run: ShippedRun {
        project_types: GO_PROJECT_TYPES,
        rule: GO_COMPLEXITY_RULE,
        expected: NO_FINDINGS,
    },
    staged: GO_COMPLEXITY_UNREAD_FILES,
    with_files: GO_COMPLEXITY_READ_FINDINGS,
    reason: READS_ONLY_ITS_ARGUMENTS,
};

/// Acceptance: the shipped Go complexity tool rule reads only the files it is
/// given, through the real gocognit pipeline.
///
/// gocognit holds no default target of its own. Measured with gocognit
/// v1.2.1, given no path: 52 lines of usage text on stderr, nothing on stdout,
/// and exit 2. A script that gave the tool that empty argument list would
/// answer a refusal, and the engine would read the refusal as a tree with no
/// finding in it.
///
/// The shipped script reaches no such run. It hands gocognit one file at a
/// time, inside the loop that drops a generated file, so the tool takes no
/// empty argument list. The head of the script counts its arguments, which is
/// the guard the `run` key of `builtin/validators/README.md` states for each
/// `files`-scope rule.
///
/// Measured over this probe with no argument: the script reported 0 findings,
/// wrote nothing to stderr, and exited 0. The same script over the two staged
/// files reports 2.
#[test]
fn the_shipped_go_complexity_tool_rule_reads_only_the_files_it_is_given() {
    verify_shipped_run_reads_only_its_arguments(&GO_COMPLEXITY_EMPTY_RUN_PROBE);
}

/// The head of the plain Go position: none.
const GO_PLAIN_HEAD: &[&str] = &[];

/// The head of the generated Go position: the header `go generate` states, and
/// the blank line under it.
///
/// The convention is one line that matches `^// Code generated .* DO NOT EDIT\.$`
/// above the first text that is neither a comment nor blank.
const GO_GENERATED_HEAD: &[&str] = &["// Code generated by protoc-gen-go. DO NOT EDIT.\n\n"];

/// The plain position, which carries no header.
const GO_PLAIN_POSITION: ShippedStagedFile = ShippedStagedFile {
    path: "plain/staged.go",
    head: GO_PLAIN_HEAD,
};

/// The generated position, which carries the header and nothing else of its
/// own.
///
/// Neither position takes a path a generator is known by, so the path can
/// decide nothing and the header is the one difference between the two.
const GO_GENERATED_POSITION: ShippedStagedFile = ShippedStagedFile {
    path: "marked/staged.go",
    head: GO_GENERATED_HEAD,
};

/// Both Go positions, in the order the work-list holds them.
const GO_GENERATED_POSITIONS: &[ShippedStagedFile] = &[GO_PLAIN_POSITION, GO_GENERATED_POSITION];

/// The one position the run must report.
const GO_GENERATED_REPORTED: &[&str] = &["plain/staged.go"];

/// The staged Go positions, and the one of them the real gocognit pipeline
/// must report.
const GO_COMPLEXITY_GENERATED_PROBE: ShippedStagedPositions = ShippedStagedPositions {
    run: ShippedRun {
        project_types: GO_PROJECT_TYPES,
        rule: GO_COMPLEXITY_RULE,
        expected: GO_GENERATED_REPORTED,
    },
    prompt_rule: COGNITIVE_COMPLEXITY_PROMPT_RULE,
    change_purpose: "one function over the complexity gate, staged in two positions",
    declarations: GO_COMPLEXITY_UNREAD_SOURCE,
    staged: GO_GENERATED_POSITIONS,
    support: NO_SUPPORT_FILES,
    reason: "the plain file reports its function, and the file whose head carries the \
             generated header reports nothing",
};

/// Acceptance: the shipped Go complexity tool rule skips a generated file,
/// through the real gocognit pipeline.
///
/// `cognitive-complexity`, the prompt rule this rule supersedes, exempts
/// generated code. gocognit reads no such header, and its one file filter,
/// `-ignore <regexp>`, reads the path and never the content: measured over
/// three files, `-ignore 'DO NOT EDIT'` dropped none of them. So the script
/// reads the head of each file it is given and drops the file that carries the
/// header.
///
/// Measured over this probe: the script without the head test reported both
/// positions, and the shipped script reports the plain position alone. The two
/// positions hold the same declarations, so the header is the one difference
/// between them.
#[test]
fn the_shipped_go_complexity_tool_rule_skips_a_generated_file() {
    verify_shipped_staged_positions_report(&GO_COMPLEXITY_GENERATED_PROBE);
}

/// One Go test function whose innermost block stands 6 levels deep, so its
/// cognitive complexity is 21 against the gate of 15.
///
/// The name and the signature are the Go test-framework convention at the
/// DEFINITION, which is the mark `cognitive-complexity` states for its test
/// carve-out.
const GO_COMPLEXITY_TEST_SOURCE: &str = r#"package probe

import "testing"

// TestBranch narrows a value, one nested block for each test.
func TestBranch(t *testing.T) {
    value := 6
    if value > 0 {
        if value > 0 {
            if value > 0 {
                if value > 0 {
                    if value > 0 {
                        if value > 0 {
                            value--
                        }
                    }
                }
            }
        }
    }
    t.Log(value)
}
"#;

/// The test-file position, which the rule measures like every other file.
const GO_TEST_POSITION: ShippedStagedFile = ShippedStagedFile {
    path: "suite/staged_test.go",
    head: GO_PLAIN_HEAD,
};

/// The test-file position alone, which is then every file of the run.
const GO_TEST_POSITIONS: &[ShippedStagedFile] = &[GO_TEST_POSITION];

/// The position the run must report, which is the whole roster.
const GO_TEST_REPORTED: &[&str] = &["suite/staged_test.go"];

/// The staged Go test file, which the real gocognit pipeline must report.
const GO_COMPLEXITY_TEST_PROBE: ShippedStagedPositions = ShippedStagedPositions {
    run: ShippedRun {
        project_types: GO_PROJECT_TYPES,
        rule: GO_COMPLEXITY_RULE,
        expected: GO_TEST_REPORTED,
    },
    prompt_rule: COGNITIVE_COMPLEXITY_PROMPT_RULE,
    change_purpose: "one test function over the complexity gate",
    declarations: GO_COMPLEXITY_TEST_SOURCE,
    staged: GO_TEST_POSITIONS,
    support: NO_SUPPORT_FILES,
    reason: "a test function stands over the gate like any other function, because \
             gocognit reads no function name and the rule states no path filter",
};

/// Acceptance: the shipped Go complexity tool rule reports a complex test
/// function, through the real gocognit pipeline.
///
/// `cognitive-complexity` exempts a test, and it names the DEFINITION as the
/// mark rather than the file name, so a complex helper in a test file stays
/// listed. gocognit holds no flag that reads a function name, and its `-test`
/// flag filters a directory walk alone: measured, `-test=false` over a NAMED
/// `_test.go` path reported the test function again.
///
/// `-ignore '_test\.go$'` would silence the file, and it would silence every
/// helper in it as well. This test holds the rule to stating no such
/// expression: a run that reported nothing here would have traded a true
/// finding for the carve-out.
#[test]
fn the_shipped_go_complexity_tool_rule_reports_a_test_file() {
    verify_shipped_staged_positions_report(&GO_COMPLEXITY_TEST_PROBE);
}

/// What the one error of a Go file gocognit could not read must name.
///
/// The script writes this text for a path that holds no file and for a file
/// the parser refuses alike, because the engine reads one broken run either
/// way and the agent needs the path.
const GO_COMPLEXITY_UNREADABLE_ERROR_PREFIX: &str = "complexity-go: gocognit could not read";

/// Where the Go file that is never written stands inside the probe repository.
const GO_COMPLEXITY_ABSENT_PATH: &str = "absent.go";

/// What the one error of an absent Go file must name.
const GO_COMPLEXITY_ABSENT_ERROR: &[&str] = &[
    GO_COMPLEXITY_UNREADABLE_ERROR_PREFIX,
    GO_COMPLEXITY_ABSENT_PATH,
];

/// The `complexity-go` probe over a path that holds no file.
const GO_COMPLEXITY_ABSENT_PROBE: ShippedNamedPath = ShippedNamedPath {
    run: ShippedRun {
        project_types: GO_PROJECT_TYPES,
        rule: GO_COMPLEXITY_RULE,
        expected: GO_COMPLEXITY_ABSENT_ERROR,
    },
    prompt_rule: COGNITIVE_COMPLEXITY_PROMPT_RULE,
    change_purpose: "a Go file that is not there",
    path: GO_COMPLEXITY_ABSENT_PATH,
    source: None,
    support: NO_SUPPORT_FILES,
};

/// Acceptance: the shipped Go complexity tool rule BREAKS on a file it cannot
/// read, through the real gocognit pipeline.
///
/// Measured with gocognit v1.2.1 over a path that holds no file: the tool
/// wrote nothing to stdout, wrote `gocognit: open ...: no such file or
/// directory` to stderr, and exited 1 — the same status it writes for a
/// finding. An earlier shape of the script ended in a pipe, so it exited 0 and
/// reported nothing, and the engine read a file the tool never judged as a
/// clean file. The `[ ! -r "$file" ]` test now names the path and exits 1
/// before gocognit runs.
#[test]
fn the_shipped_go_complexity_tool_rule_breaks_on_a_file_it_cannot_read() {
    verify_shipped_run_breaks(&GO_COMPLEXITY_ABSENT_PROBE);
}

/// A Go file that does not parse: the body of `Broken` never closes.
const GO_COMPLEXITY_UNPARSABLE_SOURCE: &str = concat!(
    "package staged\n",
    "\n",
    "func Broken(value int) int {\n",
    "\tif value > 0 {\n",
    "\t\treturn 1\n",
);

/// Where the unparsable file stands inside the probe repository.
const GO_COMPLEXITY_UNPARSABLE_PATH: &str = "unparsable.go";

/// What the one error of an unparsable Go file must name.
const GO_COMPLEXITY_UNPARSABLE_ERROR: &[&str] = &[
    GO_COMPLEXITY_UNREADABLE_ERROR_PREFIX,
    GO_COMPLEXITY_UNPARSABLE_PATH,
];

/// The `complexity-go` probe over a Go file gocognit cannot parse.
const GO_COMPLEXITY_UNPARSABLE_PROBE: ShippedNamedPath = ShippedNamedPath {
    run: ShippedRun {
        project_types: GO_PROJECT_TYPES,
        rule: GO_COMPLEXITY_RULE,
        expected: GO_COMPLEXITY_UNPARSABLE_ERROR,
    },
    prompt_rule: COGNITIVE_COMPLEXITY_PROMPT_RULE,
    change_purpose: "a Go file the parser cannot read",
    path: GO_COMPLEXITY_UNPARSABLE_PATH,
    source: Some(GO_COMPLEXITY_UNPARSABLE_SOURCE),
    support: NO_SUPPORT_FILES,
};

/// Acceptance: the shipped Go complexity tool rule BREAKS on a Go file it
/// cannot parse, through the real gocognit pipeline.
///
/// The file is readable, so the readability test admits it and gocognit reads
/// it. Measured with gocognit v1.2.1: the tool wrote nothing to stdout, wrote
/// `gocognit: ...: expected '}', found 'EOF'` to stderr, and exited 1 — the
/// same status it writes for a finding, so the status alone cannot tell the
/// two apart. The script accepts status 1 only beside a report that is a JSON
/// array of one entry or more, and this run wrote 0 bytes, so the script names
/// the file and exits 1.
#[test]
fn the_shipped_go_complexity_tool_rule_breaks_on_a_file_it_cannot_parse() {
    verify_shipped_run_breaks(&GO_COMPLEXITY_UNPARSABLE_PROBE);
}
