//! Acceptance tests for the shipped `function-length-go` tool rule.
//!
//! Each test drives the SHIPPED script over a probe Go module and reads what
//! the real funlen reported.
//!
//! The gate is a STATEMENT count, so a probe of it runs to hundreds of lines:
//! a composite literal of 300 rows is one statement, and a function of 170
//! statements is 170 lines. No `&'static str` in this file could hold those
//! shapes, so each one is built at run time and driven through
//! [`verify_staged_rows_report`].

use super::*;

use std::collections::HashMap;
use std::fs::FileTimes;
use std::hash::{DefaultHasher, Hash, Hasher};
use std::time::{Duration, SystemTime, SystemTimeError, UNIX_EPOCH};

use super::golangci_cache::GOLANGCI_CACHE_DIRECTORY;

/// What a probe of this file answers when it could not do its work.
///
/// A temporary directory, a subprocess and a file mode are each an expected
/// failure of the machine rather than a bug in the probe, so the tests below
/// answer `Result` and let the failure through. The box keeps each failure's
/// own [`std::error::Error::source`] reachable rather than flattening it into
/// a sentence, and a test that answers `Err` fails exactly as one that
/// panicked did.
type ProbeResult<T> = Result<T, Box<dyn std::error::Error>>;

/// The statement gate the shipped rule states.
///
/// 250 code lines times 0.633, the measured median statements-per-line of the
/// procedural population of the corpus the rule body names.
const GO_STATEMENT_GATE: usize = 160;

/// The statement count of a probe function that must report: one over the
/// gate, plus a margin so a later toolchain that counts one statement
/// differently does not move the probe across the gate.
const OVER_THE_GATE_STATEMENTS: usize = GO_STATEMENT_GATE + 10;

/// How many statements of a procedure the head and the tail of its body take:
/// the `state := seed` that opens it and the `return state` that closes it.
const PROCEDURE_FRAME_STATEMENTS: usize = 2;

/// The row count of a probe data shape.
///
/// The shape must stand over the 250 code lines the `function-length` prompt
/// rule states, or it could not tell a line gate from a statement gate. Each
/// row is one line, and the shape carries a few lines of its own around them.
const DATA_SHAPE_ROWS: usize = 300;

/// The module manifest of a probe repository, as the work-list holds the path.
const GO_MODULE_MANIFEST_PATH: &str = "go.mod";

/// The module manifest of a probe repository.
///
/// golangci-lint loads packages rather than files, so a probe repository with
/// no manifest loads nothing. The `go` directive names an old release for the
/// reason the shipped `go.mod` fixture states: it is the lowest version the
/// probe needs, so the installed toolchain always satisfies it and never
/// downloads another one.
const GO_MODULE_MANIFEST: &str = "module function-length-probe\n\ngo 1.21\n";

/// The package clause every probe file opens with.
const GO_PACKAGE_CLAUSE: &str = "package probe\n\n";

/// The header `go generate` states above a generated file, and the blank line
/// under it.
///
/// The convention is one line that matches `^// Code generated .* DO NOT EDIT\.$`
/// above the first text that is neither a comment nor blank.
const GO_GENERATED_HEADER: &str = "// Code generated by protoc-gen-go. DO NOT EDIT.\n\n";

/// The declarations the data shapes of a probe file need: the row a composite
/// literal holds, and the builder an option chain returns.
const GO_PROBE_DECLARATIONS: &str = concat!(
    "type probeRow struct {\n\tname  string\n\tscore int\n}\n\n",
    "type probeBuilder struct {\n\toptions []int\n}\n\n",
    "func newProbeBuilder() *probeBuilder {\n\treturn &probeBuilder{}\n}\n\n",
    "func (b *probeBuilder) option(value int) *probeBuilder {\n",
    "\tb.options = append(b.options, value)\n\treturn b\n}\n\n",
);

/// A Go function of `statements` statements, one assignment for each step
/// between the seed and the return.
///
/// This is the shape the gate exists for: every line of it is a statement, so
/// its statement count and its line count are the same number.
fn go_procedure(name: &str, statements: usize) -> String {
    let mut source = format!("func {name}(seed uint64) uint64 {{\n\tstate := seed\n");
    for step in 0..statements - PROCEDURE_FRAME_STATEMENTS {
        source.push_str(&format!("\tstate = state*31 + {step}\n"));
    }
    source.push_str("\treturn state\n}\n\n");
    source
}

/// A Go function whose whole body is one composite literal of `rows` rows.
///
/// `function-length` exempts a function that is "mostly configuration/data".
/// The literal is ONE statement however many rows it holds.
fn go_data_table(name: &str, rows: usize) -> String {
    let mut source = format!("func {name}() []probeRow {{\n\treturn []probeRow{{\n");
    for row in 0..rows {
        source.push_str(&format!("\t\t{{name: \"row{row}\", score: {row}}},\n"));
    }
    source.push_str("\t}\n}\n\n");
    source
}

/// A Go function whose whole body is one builder chain of `options` options.
///
/// `function-length` names "builder patterns with many options" as its own
/// example of the data carve-out. The chain is ONE statement however many
/// options it sets.
fn go_option_builder(name: &str, options: usize) -> String {
    let mut source = format!("func {name}() *probeBuilder {{\n\treturn newProbeBuilder()");
    for option in 0..options {
        source.push_str(&format!(".\n\t\toption({option})"));
    }
    source.push_str("\n}\n\n");
    source
}

/// A Go table-driven test of `rows` cases: the table, the walk over it, and
/// one assertion inside the walk.
///
/// This is the idiomatic Go test shape, and it is data: the table is one
/// statement, so the whole test holds four however many rows it carries.
fn go_table_driven_test(name: &str, rows: usize) -> String {
    let mut source = format!("func {name}(t *testing.T) {{\n\tcases := []probeRow{{\n");
    for row in 0..rows {
        source.push_str(&format!("\t\t{{name: \"row{row}\", score: {row}}},\n"));
    }
    source.push_str(
        "\t}\n\tfor _, c := range cases {\n\t\tif c.score < 0 {\n\t\t\tt.Errorf(\"%s\", c.name)\n\t\t}\n\t}\n}\n\n",
    );
    source
}

/// A Go test function of `statements` statements, one log call for each step.
///
/// The name and the signature are the Go test convention at the DEFINITION,
/// which is the mark the test carve-out reads.
fn go_dense_test(name: &str, statements: usize) -> String {
    let mut source = format!("func {name}(t *testing.T) {{\n");
    for step in 0..statements {
        source.push_str(&format!("\tt.Log({step})\n"));
    }
    source.push_str("}\n\n");
    source
}

/// The head of the Go declaration of `name`, as the source writes it.
///
/// funlen anchors each finding on the line its `func` keyword stands on, so
/// this is the text [`declaration_line`] reads that line from.
fn go_declaration_head(name: &str) -> String {
    format!("func {name}(")
}

/// The `path:line` entry the run must report for the declaration of `name` in
/// `source`, staged at `path`.
fn go_expected_row(path: &str, source: &str, name: &str) -> String {
    expected_row(path, source, &go_declaration_head(name))
}

/// Where the file holding the three length shapes stands inside the probe
/// repository.
const GO_SHAPES_PATH: &str = "shapes/shapes.go";

/// Acceptance: the shipped Go function-length tool rule measures statements
/// and not lines, through the real funlen pipeline.
///
/// `function-length` exempts "Functions that are mostly configuration/data
/// (e.g., builder patterns with many options)". funlen holds two dimensions
/// and ORs them, so the exemption is expressible in one shape only: the
/// statement count is the gate, and the line limit stands out of reach.
///
/// The three functions of the probe hold the same file, so the shape is the
/// one difference between them. The procedure of 170 statements reports; the
/// composite literal of 300 rows and the builder chain of 300 options each
/// stand over 250 lines, hold one statement, and stay silent.
#[test]
fn the_shipped_go_function_length_tool_rule_measures_statements_and_not_lines() {
    let source = format!(
        "{GO_PACKAGE_CLAUSE}{GO_PROBE_DECLARATIONS}{}{}{}",
        go_procedure("LongProcedure", OVER_THE_GATE_STATEMENTS),
        go_data_table("DecisionTable", DATA_SHAPE_ROWS),
        go_option_builder("OptionBuilder", DATA_SHAPE_ROWS),
    );
    let expected = go_expected_row(GO_SHAPES_PATH, &source, "LongProcedure");

    verify_staged_rows_report(
        GO_PROJECT_TYPES,
        GO_FUNCTION_LENGTH_RULE,
        &[
            (GO_MODULE_MANIFEST_PATH, GO_MODULE_MANIFEST),
            (GO_SHAPES_PATH, &source),
        ],
        &[&expected],
        "the procedure stands over the statement gate, and the data table and the builder \
         chain each hold one statement over 300 lines",
    );
}

/// Where the test file of the carve-out probe stands inside the probe
/// repository.
const GO_SUITE_TEST_PATH: &str = "suite/suite_test.go";

/// Where the one file of the suite package that is not a test stands.
///
/// A directory holding a `_test.go` file alone is a package with no
/// non-test file, and `go list` states that rather than loading it. This file
/// makes the package.
const GO_SUITE_PATH: &str = "suite/suite.go";

/// Acceptance: the shipped Go function-length tool rule reads a test from its
/// DEFINITION, through the real funlen pipeline.
///
/// `function-length` exempts "Functions explicitly marked as tests", and this
/// set names the mark: identify a test from its attribute or framework naming
/// convention at the definition, never from the file name. A complex helper
/// named `build_request` in a file called `foo_test.rs` is still a long
/// function and is still listed.
///
/// funlen writes the function's own NAME into every message it reports, so the
/// exclusion rule reads the definition. The three declarations share one file,
/// so the name is the one difference between them: `TestTable` is data and
/// stands under the gate anyway, `TestDense` stands over the gate and is a
/// test by its name and signature, and `buildRequest` stands over the gate and
/// is a helper. The run must report the helper and no other.
#[test]
fn the_shipped_go_function_length_tool_rule_reads_a_test_from_its_definition() {
    let source = format!(
        "{}{GO_PROBE_DECLARATIONS}{}{}{}",
        "package probe\n\nimport \"testing\"\n\n",
        go_table_driven_test("TestTable", DATA_SHAPE_ROWS),
        go_dense_test("TestDense", OVER_THE_GATE_STATEMENTS),
        go_procedure("buildRequest", OVER_THE_GATE_STATEMENTS),
    );
    let expected = go_expected_row(GO_SUITE_TEST_PATH, &source, "buildRequest");

    verify_staged_rows_report(
        GO_PROJECT_TYPES,
        GO_FUNCTION_LENGTH_RULE,
        &[
            (GO_MODULE_MANIFEST_PATH, GO_MODULE_MANIFEST),
            (GO_SUITE_PATH, GO_PACKAGE_CLAUSE),
            (GO_SUITE_TEST_PATH, &source),
        ],
        &[&expected],
        "the helper reports because the carve-out reads the name at the definition; a run \
         that read the path alone would silence it beside the two tests",
    );
}

/// Where the plain position of the generated-code probe stands.
const GO_PLAIN_POSITION_PATH: &str = "plain/staged.go";

/// Where the generated position of the generated-code probe stands.
///
/// Neither position takes a path a generator is known by, so the path can
/// decide nothing and the header is the one difference between the two.
const GO_GENERATED_POSITION_PATH: &str = "marked/staged.go";

/// One function over the statement gate staged at two positions, and the one
/// row a run over them must report.
///
/// The function runs to 170 lines, so no `&'static str` holds it and the
/// probe is built at run time. This shape owns the text it built, and a
/// caller that needs `(&str, &str)` pairs borrows it through
/// [`Self::files`].
struct GoGeneratedPositions {
    /// Each file of the probe repository, with the text it holds.
    staged: Vec<(&'static str, String)>,

    /// The `path:line` row a run over the repository must report, and no
    /// other.
    expected: String,
}

impl GoGeneratedPositions {
    /// Builds the probe: the function over the gate in a plain file, and the
    /// same function in a file whose head carries the header `go generate`
    /// states.
    fn build() -> Self {
        let declarations = go_procedure("LongProcedure", OVER_THE_GATE_STATEMENTS);
        let plain = format!("{GO_PACKAGE_CLAUSE}{declarations}");
        let generated = format!("{GO_GENERATED_HEADER}{GO_PACKAGE_CLAUSE}{declarations}");
        let expected = go_expected_row(GO_PLAIN_POSITION_PATH, &plain, "LongProcedure");

        Self {
            staged: vec![
                (GO_MODULE_MANIFEST_PATH, GO_MODULE_MANIFEST.to_string()),
                (GO_PLAIN_POSITION_PATH, plain),
                (GO_GENERATED_POSITION_PATH, generated),
            ],
            expected,
        }
    }

    /// Each staged file as the `(path, text)` pair a stager takes.
    fn files(&self) -> Vec<(&str, &str)> {
        self.staged
            .iter()
            .map(|(path, text)| (*path, text.as_str()))
            .collect()
    }
}

/// Drives the shipped script over a NEW probe repository holding one function
/// over the statement gate two times — in a plain file, and in a file whose
/// head carries the generated header — and holds the run to reporting the
/// plain position alone. `reason` states what the caller measures.
///
/// Each call stages a repository of its own and removes it when it returns, so
/// a caller that calls twice measures two workspaces holding the same bytes.
fn verify_the_generated_position_stays_silent(reason: &str) {
    let probe = GoGeneratedPositions::build();

    verify_staged_rows_report(
        GO_PROJECT_TYPES,
        GO_FUNCTION_LENGTH_RULE,
        &probe.files(),
        &[&probe.expected],
        reason,
    );
}

/// Acceptance: the shipped Go function-length tool rule skips a generated
/// file, through the real funlen pipeline.
///
/// `function-length` exempts generated code, and golangci-lint makes that test
/// for itself: `linters.exclusions.generated` defaults to `lax`, which drops
/// every finding in a file whose head carries the `go generate` header.
///
/// The rule states `linters.exclusions.rules` for its test carve-out, and a
/// `rules` list does not replace the `generated` default. This test holds that:
/// the two positions carry the same function over the statement gate, and the
/// run must report the plain position alone.
#[test]
fn the_shipped_go_function_length_tool_rule_skips_a_generated_file() {
    verify_the_generated_position_stays_silent(
        "the plain file reports its function, and the file whose head carries the generated \
         header reports nothing",
    );
}

/// How many workspaces the cache probe drives, one after the other, over the
/// same bytes.
///
/// Two is the whole shape: the first workspace fills the cache and is gone
/// before the second one runs, which is what two checkouts of one repository,
/// and a review in a worktree, do every day.
const CACHE_PROBE_WORKSPACES: usize = 2;

/// Acceptance: the shipped Go function-length tool rule reads the workspace it
/// ran in, over bytes another workspace already cached.
///
/// golangci-lint answers by package CONTENT and stores each finding with the
/// ABSOLUTE path of the run that first cached it, so a shared cache hands a
/// second workspace the FIRST workspace's paths. Two things then break at
/// once: the engine drops a finding it cannot place in the workspace, and the
/// generated carve-out fails OPEN, because `linters.exclusions.generated`
/// reads the head of the file at the reported path and a path that is no
/// longer there lets the finding through.
///
/// The rule names a cache directory of its own for each workspace, so the two
/// runs of this test share no cached answer. Measured with golangci-lint
/// 2.12.2 over one shared cache and this probe: the second run reported the
/// first workspace's paths, and reported the generated position beside the
/// plain one once the first workspace was gone.
#[test]
fn the_shipped_go_function_length_tool_rule_reads_the_workspace_it_ran_in() {
    for _ in 0..CACHE_PROBE_WORKSPACES {
        verify_the_generated_position_stays_silent(
            "each workspace reports its own plain file and no other row; a run answering \
             from another workspace's cache reports that workspace's paths, and lets the \
             generated position through",
        );
    }
}

/// Where the package holding the file golangci-lint cannot parse stands.
const GO_UNPARSABLE_PATH: &str = "broken/broken.go";

/// A Go file golangci-lint cannot parse: the call in the return never closes.
const GO_UNPARSABLE_SOURCE: &str = concat!(
    "package broken\n\n",
    "func Broken() int {\n\treturn undefinedSymbol(\n}\n",
);

/// What the run must say for a file golangci-lint could not parse: the row the
/// tool wrote, and the rule's own sentence.
const GO_UNPARSABLE_ERRORS: &[&str] = &[
    GO_UNPARSABLE_PATH,
    "golangci-lint reported a row of another linter",
];

/// Why a file golangci-lint cannot parse breaks the run.
const GO_UNPARSABLE_REASON: &str =
    "one Go file that does not parse drops every funlen row of the same run, so the run \
     measured no function and must say so rather than read as a clean tree";

/// Acceptance: the shipped Go function-length tool rule BREAKS on a Go file it
/// cannot parse, through the real funlen pipeline.
///
/// golangci-lint reports such a file as a `typecheck` row, and its
/// `invalid_issue` processor then answers with the typecheck rows ALONE. So the
/// probe's function of 170 statements gets no `funlen` row of its own, and the
/// run measured no function at all.
///
/// The earlier shape of this run dropped stderr and ended in `jq`, which reads
/// exactly like a clean tree: no finding, exit 0. `sah-diagnostic:` is the
/// answer for a declined ITEM of a SOUND run, and this run is not sound, so the
/// script names the row and exits 1 instead.
#[test]
fn the_shipped_go_function_length_tool_rule_breaks_on_a_file_it_cannot_parse() {
    let source = format!(
        "{GO_PACKAGE_CLAUSE}{}",
        go_procedure("LongProcedure", OVER_THE_GATE_STATEMENTS)
    );

    verify_staged_tree_breaks(
        GO_PROJECT_TYPES,
        GO_FUNCTION_LENGTH_RULE,
        &[
            (GO_MODULE_MANIFEST_PATH, GO_MODULE_MANIFEST),
            (GO_SHAPES_PATH, &source),
            (GO_UNPARSABLE_PATH, GO_UNPARSABLE_SOURCE),
        ],
        GO_UNPARSABLE_ERRORS,
        GO_UNPARSABLE_REASON,
    );
}

/// What the run must say for a workspace holding no module: the status
/// golangci-lint answered with, and the rule's own words for it.
const GO_NO_MODULE_ERRORS: &[&str] = &["golangci-lint exited", "measured no function"];

/// Why a workspace holding no module breaks the run.
const GO_NO_MODULE_REASON: &str =
    "golangci-lint loads a module, so a workspace holding none is a run that measured \
     nothing, and its report is an empty issue list a pipe reads as a clean tree";

/// Acceptance: the shipped Go function-length tool rule BREAKS on a workspace
/// that holds no Go module, through the real funlen pipeline.
///
/// Measured with golangci-lint 2.12.2 over a `.go` file with no `go.mod` beside
/// it: `Issues: []` on stdout, `typechecking error: pattern ./...: directory
/// prefix . does not contain main module or its selected dependencies` on
/// stderr, and exit 7. The report reads exactly like a clean tree, so the
/// STATUS is the only thing that separates the two, and the earlier pipe ending
/// in `jq` threw it away.
#[test]
fn the_shipped_go_function_length_tool_rule_breaks_on_a_workspace_holding_no_module() {
    let source = format!(
        "{GO_PACKAGE_CLAUSE}{}",
        go_procedure("LongProcedure", OVER_THE_GATE_STATEMENTS)
    );

    verify_staged_tree_breaks(
        GO_PROJECT_TYPES,
        GO_FUNCTION_LENGTH_RULE,
        &[(GO_SHAPES_PATH, &source)],
        GO_NO_MODULE_ERRORS,
        GO_NO_MODULE_REASON,
    );
}

/// Where the file nobody may read stands inside the probe module.
///
/// It holds a package of its own, and that package is the only one the probe
/// workspace carries: a file the tool cannot open is a package golangci-lint
/// cannot load, so a workspace holding that package alone measures nothing.
const GO_UNREADABLE_PATH: &str = "noread/unreadable.go";

/// What the file nobody may read holds.
///
/// The source is ordinary and stands under the gate, so a run that DID read it
/// would report no finding — which is the clean answer this rule must not give
/// for a file it never read.
const GO_UNREADABLE_SOURCE: &str = "package noread\n\nfunc Short() int {\n\treturn 1\n}\n";

/// What the run must say for a workspace whose one Go package golangci-lint
/// could not read: the path the tool named, and the rule's own words for the
/// status.
const GO_UNREADABLE_ERRORS: &[&str] = &[
    GO_UNREADABLE_PATH,
    "golangci-lint exited",
    "measured no function",
];

/// Why a workspace whose one package golangci-lint cannot read breaks the run.
const GO_UNREADABLE_REASON: &str =
    "the one package of the workspace is the package golangci-lint cannot load, so the \
     run measured no function at all and must say so";

/// Acceptance: the shipped Go function-length tool rule BREAKS on a Go file it
/// may not read, through the real funlen pipeline.
///
/// golangci-lint refuses such a file with
/// `level=error msg="[linters_context] typechecking error: open <path>:
/// permission denied"` on stderr, and it writes no row for that package. The
/// probe workspace holds that package and NO OTHER, so the run measured no
/// function at all. Measured with golangci-lint 2.12.2 over this workspace,
/// the cache directory made empty for every round and removed after it:
/// `Issues: []` on the report at exit 7, in 20 rounds at `GOMAXPROCS=1` and 20
/// rounds at `GOMAXPROCS=18`.
///
/// The workspace holds no second package on purpose. What a run reports for
/// the OTHER packages of such a workspace is a race inside golangci-lint
/// rather than a fact about the tool, and the rule body states that
/// measurement under "A file it cannot read, which costs the run the package
/// it never read". A probe that stages a readable function beside this file
/// therefore holds the run to one branch of a race no test can own: measured,
/// that shape failed 5 of 6 rounds under `GOMAXPROCS=1`.
///
/// The earlier shape of this run dropped stderr and ended in `jq`, so that run
/// read as a clean tree. The probe takes every permission off the file, which
/// is a mode, so it runs on unix alone.
#[cfg(unix)]
#[test]
fn the_shipped_go_function_length_tool_rule_breaks_on_a_file_it_may_not_read() {
    let staged = [(GO_MODULE_MANIFEST_PATH, GO_MODULE_MANIFEST)];
    let named: Vec<&str> = staged
        .iter()
        .map(|(path, _)| *path)
        .chain(std::iter::once(GO_UNREADABLE_PATH))
        .collect();
    let unreadable = ShippedUnreadableFile::Forbidden(GO_UNREADABLE_SOURCE);
    let prepare = |repo: &Path| stage_probe_unreadable(repo, GO_UNREADABLE_PATH, &unreadable);
    let staging = ShippedStaging {
        prepare: &prepare,
        ..ShippedStaging::of(&staged)
    };

    verify_staging_breaks(
        GO_PROJECT_TYPES,
        GO_FUNCTION_LENGTH_RULE,
        &staging,
        &named,
        GO_UNREADABLE_ERRORS,
        GO_UNREADABLE_REASON,
    );
}

/// The name the shipped script calls the linter by.
const GO_TOOL_BINARY_NAME: &str = "golangci-lint";

/// The line a stubbed golangci-lint answers a run whose cache already holds the
/// finding, and which met one file it could not read.
///
/// Every byte of it is the answer the real golangci-lint 2.12.2 gave, measured
/// over one workspace run three times: the file unreadable on a cold cache, the
/// file readable, and the file unreadable again. The third run reported the
/// `funlen` row out of the cache the second run filled, wrote the
/// `[linters_context]` line to stderr, and exited 1.
///
/// The stub is what makes that answer DETERMINISTIC. A warm cache gives it
/// every time — measured over one workspace linted with the file readable and
/// then unreadable, 20 rounds at `GOMAXPROCS=1` and 20 at `GOMAXPROCS=18`, all
/// 40 reporting the row at exit 1. A workspace whose cache is cold gives it
/// too, but only when the sound package wins a race inside golangci-lint: 18
/// of 24 fresh workspaces at `GOMAXPROCS=1`, and 0 of 40 at the default. The
/// stub therefore stands in for the cache rather than for a shape no probe
/// could stage.
const GO_DECLINED_ANSWER: &str = concat!(
    "  printf '{\"Issues\":[{\"FromLinter\":\"funlen\",\"Text\":\"Function %s has too many ",
    "statements (170 > 160)\",\"Pos\":{\"Filename\":\"%s/shapes/shapes.go\",\"Line\":3}}]}\\n' ",
    "\"'LongProcedure'\" \"$PWD\"\n",
    "  printf 'level=error msg=\"[linters_context] typechecking error: open ",
    "%s/noread/unreadable.go: permission denied\"\\n' \"$PWD\" >&2\n",
    "  exit 1"
);

/// Acceptance: the shipped Go function-length tool rule DECLINES a Go file it
/// may not read, over a run that still reported its findings.
///
/// A run whose cache already holds the answer for every package it CAN load
/// reports those findings beside the `[linters_context]` line for the package
/// it cannot. That run judged the code and could not judge ONE item, which is
/// the shape `builtin/validators/README.md` states a `sah-diagnostic:` line at
/// exit 0 for: an `exit 1` there would throw away every finding the run did
/// make.
///
/// The stub answers with the bytes the real golangci-lint 2.12.2 wrote for that
/// run, because a probe that staged the workspace would read that answer only
/// when a race inside golangci-lint fell its way. The probe leads `PATH` with
/// the stub, which is process state, so it stands under
/// `#[serial_test::serial(env)]`.
#[cfg(unix)]
#[test]
#[serial_test::serial(env)]
fn the_shipped_go_function_length_tool_rule_declines_a_file_it_may_not_read() -> ProbeResult<()> {
    let run = drive_shipped_script_with_stub(
        GO_PROJECT_TYPES,
        GO_FUNCTION_LENGTH_RULE,
        &[(GO_MODULE_MANIFEST_PATH, GO_MODULE_MANIFEST)],
        NO_SCRIPT_FILES,
        GO_TOOL_BINARY_NAME,
        GO_DECLINED_ANSWER,
    );
    // A script handed an item it cannot judge must judge the rest and exit 0.
    // A failure here is therefore the answer of the run, and the test fails on
    // it with the script's own stderr rather than with a sentence of its own.
    let outcome = run.outcome?;

    assert_eq!(
        sorted_names(&finding_rows(&outcome, &run.repo_root)),
        vec![format!("{GO_SHAPES_PATH}:3")],
        "the run must report every finding it made, or one file it could not read throws \
         away the work the run did do"
    );
    let stated = script_diagnostics(&outcome, &run.repo_root);
    assert_eq!(
        stated.len(),
        1,
        "the run must state the one item it declined; it stated {stated:?}"
    );
    assert!(
        stated[0].contains(GO_UNREADABLE_PATH),
        "the diagnostic must name the file it declined; it said '{}'",
        stated[0]
    );
    Ok(())
}

/// How many runs of the shipped script the lock probe starts together.
///
/// golangci-lint takes ONE file lock, and the lock stands in the cache
/// directory the run reads — which the shipped script names for the workspace,
/// so the runs of one workspace share it. Measured over this probe without the
/// `allow-serial-runners` key, three rounds from a cold cache and three from a
/// warm one: 0 of 4 runs started together reported nothing, and 3 of 8 reported
/// nothing, in each of the six rounds. Four runs never clash, so the probe
/// needs eight.
const LOCK_PROBE_RUNS: usize = 8;

/// The run the lock probe drives: the shipped Go function-length rule over a
/// Go workspace.
///
/// The run states no `expected`, because the probe compares the runs against
/// each other rather than against a list this constant holds.
const GO_FUNCTION_LENGTH_LOCK_RUN: ShippedRun = ShippedRun {
    project_types: GO_PROJECT_TYPES,
    rule: GO_FUNCTION_LENGTH_RULE,
    expected: NO_FINDINGS,
};

/// Acceptance: the shipped Go function-length tool rule reports while another
/// instance holds the lock, through the real funlen pipeline.
///
/// `run: allow-serial-runners: true` makes a second instance WAIT for the
/// lock. Without the key it stops with `Error: parallel golangci-lint is
/// running` on stderr, writes nothing to stdout, and exits 3 — so the run
/// judges nothing, and the key is what keeps every run measuring.
///
/// Measured with golangci-lint 2.12.2 over this probe, three rounds from a
/// cold cache and three from a warm one: without the key 3 of 8 runs reported
/// nothing in each of the six rounds, and each of those three carried the lock
/// error on stderr at exit 3. With the key all eight reported the one finding,
/// in each of the six rounds.
///
/// The status gate the rule now carries turns that stop into a broken run
/// rather than a clean file, so a clashing run fails this test on the status
/// rather than on the empty row list.
#[test]
fn the_shipped_go_function_length_tool_rule_reports_while_another_run_holds_the_lock() {
    let source = format!(
        "{GO_PACKAGE_CLAUSE}{}",
        go_procedure("LongProcedure", OVER_THE_GATE_STATEMENTS)
    );
    let expected = sorted_names(&[go_expected_row(GO_SHAPES_PATH, &source, "LongProcedure")]);

    let reported = rows_of_runs_started_together(
        &GO_FUNCTION_LENGTH_LOCK_RUN,
        &[
            (GO_MODULE_MANIFEST_PATH, GO_MODULE_MANIFEST),
            (GO_SHAPES_PATH, &source),
        ],
        NO_SCRIPT_FILES,
        LOCK_PROBE_RUNS,
    );

    assert!(
        reported.iter().all(|run| *run == expected),
        "every run started together must report {expected:?}, because a second instance \
         waits for the lock rather than stopping; a run that stopped judged nothing at \
         all: {reported:?}"
    );
}

/// The polynomial POSIX `cksum` reduces its input with.
///
/// The shipped rule keyed its cache with `cksum` before this test, and the
/// probe below stages the pair of working directories that key merged. Only
/// `cksum` names such a pair, so the probe computes it.
const CKSUM_POLYNOMIAL: u32 = 0x04C1_1DB7;

/// How many entries the `cksum` table holds: one for each byte value.
const CKSUM_TABLE_ENTRIES: usize = 256;

/// How many bits one byte holds, as the reduction steps over its input.
const BITS_IN_A_BYTE: u32 = 8;

/// Which bit of the running state the reduction reads its table index from:
/// the top byte of a 32-bit word.
const CKSUM_HIGH_BYTE_SHIFT: u32 = 24;

/// The bit the reduction tests before each shift.
const CKSUM_TOP_BIT: u32 = 0x8000_0000;

/// The `cksum` table for [`CKSUM_POLYNOMIAL`].
type CksumTable = [u32; CKSUM_TABLE_ENTRIES];

/// Builds the `cksum` table for [`CKSUM_POLYNOMIAL`].
fn cksum_table() -> CksumTable {
    let mut table = [0_u32; CKSUM_TABLE_ENTRIES];
    for (byte, entry) in table.iter_mut().enumerate() {
        let mut state = (byte as u32) << CKSUM_HIGH_BYTE_SHIFT;
        for _ in 0..BITS_IN_A_BYTE {
            state = match state & CKSUM_TOP_BIT {
                0 => state << 1,
                _ => (state << 1) ^ CKSUM_POLYNOMIAL,
            };
        }
        *entry = state;
    }
    table
}

/// The bytes `cksum` folds the byte COUNT in as: the count little end first,
/// and no byte at all for a count of zero.
fn cksum_length_bytes(mut count: usize) -> Vec<u8> {
    let mut bytes = Vec::new();
    while count > 0 {
        bytes.push(count as u8);
        count >>= BITS_IN_A_BYTE;
    }
    bytes
}

/// The checksum POSIX `cksum` writes for `bytes`.
fn posix_cksum(table: &CksumTable, bytes: &[u8]) -> u32 {
    let mut state = 0_u32;
    for byte in bytes.iter().copied().chain(cksum_length_bytes(bytes.len())) {
        let index = ((state >> CKSUM_HIGH_BYTE_SHIFT) as u8) ^ byte;
        state = (state << BITS_IN_A_BYTE) ^ table[index as usize];
    }
    !state
}

/// The cache-directory name the rule wrote for `path` before this change:
/// `printf '%s' "$PWD" | cksum | tr -dc '0-9'`.
///
/// `cksum` writes the checksum and the byte COUNT, and `tr` glues the digits
/// of both together. Two paths of the same length therefore share this name
/// exactly when they share the 32-bit checksum.
fn old_cache_key(table: &CksumTable, path: &str) -> String {
    format!("{} {}", posix_cksum(table, path.as_bytes()), path.len())
        .chars()
        .filter(char::is_ascii_digit)
        .collect()
}

/// The alphabet a candidate working-directory name is written in.
const CANDIDATE_NAME_ALPHABET: &[u8] = b"abcdefghijklmnopqrstuvwxyz0123456789";

/// How many characters a candidate working-directory name holds.
///
/// Both names take this one width, so both paths hold the same number of
/// bytes and the byte-count half of the old key matches whenever the checksum
/// half does.
///
/// The width stands past four characters on purpose. Measured: a search that
/// varied four characters of a name met no pair in 4000000 candidates,
/// because the reduction is one to one over any four bytes; a search that
/// varies twelve meets one in about 225000.
const CANDIDATE_NAME_WIDTH: usize = 12;

/// How many candidate names the search reads before it gives up.
///
/// The checksum is 32 bits wide, so a birthday search over it meets a pair
/// after about 82000 candidates. The limit stands far past that, and a search
/// that reaches it states so rather than answering a pair it never found.
const CANDIDATE_NAME_LIMIT: usize = 1_000_000;

/// The candidate working-directory name for `index`.
///
/// The index is hashed first, so consecutive candidates differ across the
/// whole width of the name rather than in their first characters alone.
/// `DefaultHasher` carries fixed keys, so the walk is the same on every run.
fn candidate_name(index: usize) -> String {
    let mut hasher = DefaultHasher::new();
    index.hash(&mut hasher);
    let mut draw = hasher.finish();
    let alphabet_width = CANDIDATE_NAME_ALPHABET.len() as u64;
    (0..CANDIDATE_NAME_WIDTH)
        .map(|_| {
            let letter = CANDIDATE_NAME_ALPHABET[(draw % alphabet_width) as usize];
            draw /= alphabet_width;
            char::from(letter)
        })
        .collect()
}

/// Two names for sibling working directories under `root` whose paths the OLD
/// cache key merged into one directory.
///
/// A birthday search over a 32-bit checksum meets a pair long before
/// [`CANDIDATE_NAME_LIMIT`], and no pigeonhole makes that certain, so a search
/// that reads the whole limit answers the failure rather than a pair it never
/// found.
fn workspace_names_one_checksum_merged(
    table: &CksumTable,
    root: &Path,
) -> ProbeResult<(String, String)> {
    let mut seen: HashMap<String, String> = HashMap::new();
    for index in 0..CANDIDATE_NAME_LIMIT {
        let name = candidate_name(index);
        let key = old_cache_key(table, &root.join(&name).to_string_lossy());
        match seen.get(&key) {
            Some(earlier) if *earlier != name => return Ok((earlier.clone(), name)),
            _ => {
                seen.insert(key, name);
            }
        }
    }
    Err(format!("the search met no pair of names one checksum merges under {root:?}").into())
}

/// Acceptance: the shipped Go function-length tool rule reads the workspace it
/// ran in, over two workspaces one CHECKSUM merged.
///
/// The sibling test above stages two workspaces that differ in every way, so
/// it holds the rule only where the key already separates them. This one
/// stages the pair the key must separate and could not: two directories whose
/// paths carry the same `cksum` checksum over the same number of bytes.
///
/// Under a checksum key the two runs share one cache directory, and
/// golangci-lint answers by package CONTENT with the ABSOLUTE path of the run
/// that first cached it. Measured with golangci-lint 2.12.2 over this exact
/// pair: the second run reported the FIRST workspace's `plain/staged.go`,
/// which stands outside the second workspace, so the engine drops it and the
/// rule reports nothing. A 256-bit digest of the path separates the pair, and
/// each run then reports its own plain position.
///
/// The pair is searched for rather than written down, because the working
/// directory is a temporary path this run is given and no constant can name
/// it.
#[test]
fn the_shipped_go_function_length_tool_rule_reads_the_workspace_one_checksum_merged(
) -> ProbeResult<()> {
    let loader = builtin_loader();
    require_tool_installed(&loader, GO_PROJECT_TYPES, GO_FUNCTION_LENGTH_RULE);
    let shipped = required_shipped_tool_rule(&loader, GO_FUNCTION_LENGTH_RULE);
    let work = tempfile::tempdir()?;
    let root = probe_repository_root(work.path());
    let table = cksum_table();
    let (first, second) = workspace_names_one_checksum_merged(&table, &root)?;
    assert_eq!(
        old_cache_key(&table, &root.join(&first).to_string_lossy()),
        old_cache_key(&table, &root.join(&second).to_string_lossy()),
        "the probe must stage two working directories one checksum merged, or it holds \
         the rule over a pair the old key already separated"
    );

    let probe = GoGeneratedPositions::build();
    let args = script_args(shipped.scope, NO_SCRIPT_FILES);
    for name in [&first, &second] {
        let repo = root.join(name);
        stage_probe_files(&repo, probe.files());
        let repo_root = probe_repository_root(&repo);

        // Each run must judge its own workspace and exit 0. A failure here is
        // therefore the answer of the run, and the test fails on it with the
        // script's own stderr rather than with a sentence of its own.
        let reported = run_script(&shipped.script, &repo_root, &args)?;

        assert_eq!(
            sorted_names(&finding_rows(&reported, &repo_root)),
            vec![probe.expected.clone()],
            "each of the two workspaces must report its OWN plain position; a run \
             answering out of a cache the other one filled reports that workspace's \
             paths, which stand outside this one"
        );
    }
    Ok(())
}

/// How old the stale cache directory of the sweep probe is, in days.
///
/// The shipped sweep removes a directory nothing has touched for six days or
/// more, so thirty stands well past the cut and the probe measures the sweep
/// rather than the boundary.
const STALE_CACHE_AGE_DAYS: u64 = 30;

/// How old the fresh cache directory of the sweep probe is: nothing at all.
const FRESH_CACHE_AGE_DAYS: u64 = 0;

/// How many seconds one day holds.
const SECONDS_IN_A_DAY: u64 = 24 * 60 * 60;

/// A cache-directory name no other run of this probe writes.
///
/// The sweep reads every directory under the one cache parent, whatever its
/// name, so two probes running together must not stage the same one.
///
/// The name carries the clock, which a machine set before the epoch has none
/// of, so the reading is answered rather than taken for granted.
fn unique_cache_name(role: &str) -> Result<String, SystemTimeError> {
    let stamp = SystemTime::now().duration_since(UNIX_EPOCH)?;
    Ok(format!(
        "probe-{role}-{}-{}",
        std::process::id(),
        stamp.as_nanos()
    ))
}

/// Makes a cache directory named `name` under the one cache parent, aged so
/// that nothing has touched it for `age_days`, and answers its path.
///
/// Each step is a filesystem call, and a full disk or a mode that stops it is
/// a state of the machine rather than a bug in the probe, so the failure is
/// answered and the test fails on it.
fn stage_cache_directory(name: &str, age_days: u64) -> std::io::Result<PathBuf> {
    let directory = std::env::temp_dir()
        .join(GOLANGCI_CACHE_DIRECTORY)
        .join(name);
    std::fs::create_dir_all(&directory)?;
    let touched = SystemTime::now() - Duration::from_secs(age_days * SECONDS_IN_A_DAY);
    std::fs::File::open(&directory)?.set_times(FileTimes::new().set_modified(touched))?;
    Ok(directory)
}

/// Acceptance: the shipped Go function-length tool rule sweeps the cache
/// directories nothing names any more.
///
/// The cache stands between runs on purpose — the lock golangci-lint takes
/// stands inside it, and a warm cache is what lets a run that met one file it
/// could not read still report the findings it made. So the rule cannot
/// remove the directory it just used, and a run over a temporary workspace
/// therefore leaves one behind for ever. Measured on one machine: 6609 such
/// directories, 422804 KiB, and nothing older than three days only because
/// the platform swept them.
///
/// golangci-lint states the lifetime itself: `internal/go/cache/cache.go`
/// sets `trimLimit = 5 * 24 * time.Hour` and drops every entry older than
/// that from a cache it is GIVEN. It never removes a directory nobody names
/// again, which is the whole pile-up, and a directory past that limit holds
/// nothing golangci-lint would have kept.
///
/// The probe stages one directory nothing has touched for thirty days beside
/// one touched now, and holds the run to removing the first and keeping the
/// second — so the sweep reads the age and not the name.
#[test]
fn the_shipped_go_function_length_tool_rule_sweeps_a_stale_cache_directory() -> ProbeResult<()> {
    let loader = builtin_loader();
    require_tool_installed(&loader, GO_PROJECT_TYPES, GO_FUNCTION_LENGTH_RULE);
    let stale = stage_cache_directory(&unique_cache_name("stale")?, STALE_CACHE_AGE_DAYS)?;
    let fresh = stage_cache_directory(&unique_cache_name("fresh")?, FRESH_CACHE_AGE_DAYS)?;

    verify_the_generated_position_stays_silent(
        "the run reports its own plain position while it sweeps the stale cache \
         directories beside it",
    );

    let swept = !stale.exists();
    let kept = fresh.exists();
    std::fs::remove_dir_all(&stale).ok();
    std::fs::remove_dir_all(&fresh).ok();
    assert!(
        swept,
        "the run must remove a cache directory nothing has touched for \
         {STALE_CACHE_AGE_DAYS} days; {stale:?} is still there, so every run over a \
         temporary workspace leaves one behind for ever"
    );
    assert!(
        kept,
        "the run must keep a cache directory another run just touched; {fresh:?} is \
         gone, so the sweep reads the name rather than the age and takes the cache a \
         live workspace is using"
    );
    Ok(())
}
