//! Acceptance tests for the shipped `function-length-python` tool rule.
//!
//! Each test drives the SHIPPED script over a probe Python tree and reads what
//! the real ruff reported, end to end.
//!
//! One module stands for each language of the family, because one file for the
//! whole family runs past the byte cap a review prompt holds.

use super::*;

/// The head of the plain Python position: none.
const PYTHON_PLAIN_HEAD: &[&str] = &[];

/// The head of the generated Python position: the header the protocol buffer
/// compiler writes, and the blank line under it.
///
/// Python states no generated-file header convention of its own. This is one
/// generator's first line, which is why the rule reproduces no carve-out from
/// it.
const PYTHON_GENERATED_HEAD: &[&str] =
    &["# Generated by the protocol buffer compiler.  DO NOT EDIT!\n\n"];

/// The plain position, which carries no header.
const PYTHON_PLAIN_POSITION: ShippedStagedFile = ShippedStagedFile {
    path: "plain/staged.py",
    head: PYTHON_PLAIN_HEAD,
};

/// The generated position, which carries the header and nothing else of its
/// own.
///
/// Neither position takes a path a generator is known by, so the path can
/// decide nothing and the header is the one difference between the two.
const PYTHON_GENERATED_POSITION: ShippedStagedFile = ShippedStagedFile {
    path: "marked/staged.py",
    head: PYTHON_GENERATED_HEAD,
};

/// A Python function of 190 statements, which stands over the `PLR0915` gate
/// of 180. `PLR0915` counts a statement rather than a line, and a semicolon
/// separates one statement from the next, so 19 lines carry the whole count.
const PYTHON_LENGTH_UNREAD_SOURCE: &str = r#"def long_function():
    value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0
    value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0
    value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0
    value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0
    value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0
    value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0
    value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0
    value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0
    value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0
    value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0
    value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0
    value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0
    value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0
    value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0
    value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0
    value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0
    value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0
    value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0
    value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0; value = 0
    return 0
"#;

/// Every Python file staged in the probe repository the function-length
/// script is given none of.
const PYTHON_LENGTH_UNREAD_FILES: &[(&str, &str)] = &[
    ("top.py", PYTHON_LENGTH_UNREAD_SOURCE),
    ("deep/nested/other.py", PYTHON_LENGTH_UNREAD_SOURCE),
];

/// Each finding the Python function-length script reports over the two files
/// it is given, as `path:line`.
const PYTHON_LENGTH_READ_FINDINGS: &[&str] = &["deep/nested/other.py:1", "top.py:1"];

/// The `function-length-python` probe over a run that is given no file.
const PYTHON_LENGTH_EMPTY_RUN_PROBE: ShippedEmptyRun = ShippedEmptyRun {
    run: ShippedRun {
        project_types: PYTHON_PROJECT_TYPES,
        rule: PYTHON_FUNCTION_LENGTH_RULE,
        expected: NO_FINDINGS,
    },
    staged: PYTHON_LENGTH_UNREAD_FILES,
    with_files: PYTHON_LENGTH_READ_FINDINGS,
    reason: READS_ONLY_ITS_ARGUMENTS,
};

/// Acceptance: the shipped Python function-length tool rule reads only the
/// files it is given, through the real ruff pipeline.
///
/// ruff holds a default target: given no path it walks the tree under the
/// working directory, so a script that handed the tool an empty argument list
/// would judge files the work-list never named. Measured over this probe with
/// no argument: without the guard the script reported 2 findings and exited 0;
/// with the guard it reports none and exits 0. The same script over the two
/// staged files reports 2.
#[test]
fn the_shipped_python_function_length_tool_rule_reads_only_the_files_it_is_given() {
    verify_shipped_run_reads_only_its_arguments(&PYTHON_LENGTH_EMPTY_RUN_PROBE);
}

/// The statement gate the shipped `function-length-python` rule states.
///
/// 250 code lines times 0.72, the measured median statements-per-line of the
/// long functions of the corpus the rule body names.
const PYTHON_STATEMENT_GATE: usize = 180;

/// The statement count of a probe function that must report: over the gate,
/// plus a margin so a later ruff that counts one statement differently does
/// not move the probe across the gate.
const OVER_THE_GATE_STATEMENTS: usize = PYTHON_STATEMENT_GATE + 10;

/// The row count of a probe data shape.
///
/// The shape must stand over the 250 code lines the `function-length` prompt
/// rule states, or it could not tell a line gate from a statement gate. Each
/// row is one line, and the shape carries a few lines of its own around them.
const PYTHON_DATA_SHAPE_ROWS: usize = 300;

/// The head of the Python declaration of `name`, as the source writes it.
///
/// `PLR0915` anchors each finding on the NAME of the function, and a Python
/// name stands on the `def` line, so this is the text [`declaration_line`]
/// reads that line from.
fn python_declaration_head(name: &str) -> String {
    format!("def {name}(")
}

/// The `path:line` entry the run must report for the declaration of `name` in
/// `source`, staged at `path`.
fn python_expected_row(path: &str, source: &str, name: &str) -> String {
    expected_row(path, source, &python_declaration_head(name))
}

/// A Python function of `statements` statements, one assignment for each step.
///
/// This is the shape the gate exists for: every line of the body is a
/// statement, so its statement count and its line count are the same number.
fn python_procedure(name: &str, statements: usize) -> String {
    let body: String = (0..statements)
        .map(|step| format!("    value = {step}\n"))
        .collect();
    format!("def {name}():\n{body}\n\n")
}

/// A Python function whose whole body is one mapping literal of `rows` rows.
///
/// `function-length` exempts a function that is "mostly configuration/data".
/// The literal is ONE expression however many rows it holds, and `PLR0915`
/// counts statements.
fn python_data_table(name: &str, rows: usize) -> String {
    let body: String = (0..rows)
        .map(|row| format!("        \"key{row}\": {row},\n"))
        .collect();
    format!("def {name}():\n    return {{\n{body}    }}\n\n\n")
}

/// A Python class holding one `__init__` that sets `fields` fields, with
/// `annotation` written after the `def` line's colon.
///
/// `function-length` exempts "Initialization functions that set many fields".
/// Each `self.x = ...` is one statement, so this shape is the one the gate
/// cannot tell from a procedure.
fn python_field_setting_class(class: &str, fields: usize, annotation: &str) -> String {
    let body: String = (0..fields)
        .map(|field| format!("        self.field_{field} = {field}\n"))
        .collect();
    format!("class {class}:\n    def __init__(self):{annotation}\n{body}\n\n")
}

/// The annotation an author writes to exempt one function.
const PYTHON_LENGTH_ANNOTATION: &str = "  # noqa: PLR0915";

/// No annotation at all, which is what the bare position of a probe carries.
const PYTHON_NO_ANNOTATION: &str = "";

/// Where the file of the test carve-out probe stands inside the probe
/// repository.
///
/// The name is one pytest collects from, so a run that read the PATH would
/// silence the helper standing beside the test.
const PYTHON_LENGTH_SUITE_PATH: &str = "suite/staged_test.py";

/// Acceptance: the shipped Python function-length tool rule reads a test from
/// its DEFINITION, through the real ruff pipeline.
///
/// `function-length` exempts "Functions explicitly marked as tests". The mark
/// stands at the DEFINITION, and never at the file name: a long helper named
/// `build_request` in a file called `staged_test.py` is still a long function
/// and is still listed.
///
/// ruff writes no name into its message, and it anchors each `PLR0915` finding
/// on the NAME of the function it measured, so the script reads the definition
/// out of that range. The three declarations share one file, so the name is the
/// one difference between them: `test_dense` stands over the gate and is a test
/// by its name, `build_request` stands over the gate and is a helper, and
/// `option_table` holds 300 rows of data in one statement. The run must report
/// the helper and no other.
#[test]
fn the_shipped_python_function_length_tool_rule_reads_a_test_from_its_definition() {
    let source = format!(
        "{}{}{}",
        python_procedure("test_dense", OVER_THE_GATE_STATEMENTS),
        python_procedure("build_request", OVER_THE_GATE_STATEMENTS),
        python_data_table("option_table", PYTHON_DATA_SHAPE_ROWS),
    );
    let expected = python_expected_row(PYTHON_LENGTH_SUITE_PATH, &source, "build_request");

    verify_staged_rows_report(
        PYTHON_PROJECT_TYPES,
        PYTHON_FUNCTION_LENGTH_RULE,
        &[(PYTHON_LENGTH_SUITE_PATH, &source)],
        &[&expected],
        "the helper reports because the carve-out reads the name at the definition; a run \
         that read the path alone would silence it beside the test",
    );
}

/// Where the bare initializer of the field-setting probe stands.
const PYTHON_BARE_INITIALIZER_PATH: &str = "bare/editor.py";

/// Where the annotated initializer of the field-setting probe stands.
///
/// Neither position takes a path a carve-out could read, so the annotation is
/// the one difference between the two.
const PYTHON_ANNOTATED_INITIALIZER_PATH: &str = "annotated/editor.py";

/// Acceptance: the shipped Python function-length tool rule REPORTS a
/// field-setting initializer, and the annotation answers it, through the real
/// ruff pipeline.
///
/// `function-length` exempts "Initialization functions that set many fields".
/// `PLR0915` counts each `self.x = ...` as one statement, so an initializer
/// over the gate reports like any other function, and this test holds the gap
/// measured rather than left to be discovered. The rule body states why no
/// mechanism answers it: the widest field setter of the corpus sets 55 fields
/// against a gate of 180.
///
/// The two positions hold the same class of 190 field-setting statements, so
/// the `# noqa: PLR0915` is the one difference between them.
#[test]
fn the_shipped_python_function_length_tool_rule_reports_a_field_setting_initializer() {
    let bare = python_field_setting_class("Editor", OVER_THE_GATE_STATEMENTS, PYTHON_NO_ANNOTATION);
    let annotated =
        python_field_setting_class("Editor", OVER_THE_GATE_STATEMENTS, PYTHON_LENGTH_ANNOTATION);
    let expected = python_expected_row(PYTHON_BARE_INITIALIZER_PATH, &bare, "__init__");

    verify_staged_rows_report(
        PYTHON_PROJECT_TYPES,
        PYTHON_FUNCTION_LENGTH_RULE,
        &[
            (PYTHON_BARE_INITIALIZER_PATH, &bare),
            (PYTHON_ANNOTATED_INITIALIZER_PATH, &annotated),
        ],
        &[&expected],
        "an initializer that sets more fields than the gate allows reports like any other \
         function, and the annotation on its `def` line is the answer",
    );
}

/// Acceptance: the shipped Python function-length tool rule REPORTS a
/// generated file, through the real ruff pipeline.
///
/// `function-length` exempts generated code. ruff holds no generated-file
/// heuristic — measured, no option of its 166 names one — and Python states no
/// header convention for one either.
///
/// The two positions hold the same function over the gate, so the header is
/// the one difference between them, and the run must report both.
#[test]
fn the_shipped_python_function_length_tool_rule_reports_a_generated_file() {
    let declarations = python_procedure("long_procedure", OVER_THE_GATE_STATEMENTS);
    let generated = format!("{}{declarations}", PYTHON_GENERATED_HEAD.concat());
    let expected = [
        python_expected_row(PYTHON_PLAIN_POSITION.path, &declarations, "long_procedure"),
        python_expected_row(PYTHON_GENERATED_POSITION.path, &generated, "long_procedure"),
    ];

    verify_staged_rows_report(
        PYTHON_PROJECT_TYPES,
        PYTHON_FUNCTION_LENGTH_RULE,
        &[
            (PYTHON_PLAIN_POSITION.path, &declarations),
            (PYTHON_GENERATED_POSITION.path, &generated),
        ],
        &[&expected[0], &expected[1]],
        "a generated Python file reports like any other file, because ruff reads no header \
         and Python states no header convention to read",
    );
}

/// A Python file that does not parse: the body of `broken` holds no statement.
const PYTHON_LENGTH_UNPARSABLE_SOURCE: &str =
    concat!("def broken(value):\n", "    if value > 0:\n",);

/// Where the Python file ruff cannot parse stands inside the probe repository.
const PYTHON_LENGTH_UNPARSABLE_PATH: &str = "unparsable.py";

/// Acceptance: the shipped Python function-length tool rule DECLINES a Python
/// file it cannot parse, through the real ruff pipeline.
///
/// ruff writes a file it cannot parse onto the SAME report as a finding, under
/// `"code": "invalid-syntax"`. Measured with ruff 0.14.5 over a file whose `if`
/// body never opens beside one function of 190 statements: two rows on the
/// report — the `PLR0915` count of the file it read AND the parse failure — at
/// exit 1, and nothing on stderr. ruff measured the other file, so the finding
/// is there to lose.
///
/// A script that read every row as a finding reported the parse failure as a
/// function-length finding, and a script that dropped every other code would
/// read the unparsable file as clean. An `exit 1` answers neither: it fails the
/// WHOLE run, so the `PLR0915` finding of the file ruff DID measure goes away
/// with it. The parse failure is one declined item of a sound run, so the
/// script states it under the `sah-diagnostic:` marker at exit 0.
#[test]
fn the_shipped_python_function_length_tool_rule_declines_a_file_it_cannot_parse() {
    let judged = python_procedure("long_procedure", OVER_THE_GATE_STATEMENTS);
    let expected = python_expected_row(PYTHON_LENGTH_JUDGED_PATH, &judged, "long_procedure");

    verify_unjudged_file_is_declined(
        PYTHON_PROJECT_TYPES,
        PYTHON_FUNCTION_LENGTH_RULE,
        &[
            (PYTHON_LENGTH_JUDGED_PATH, &judged),
            (
                PYTHON_LENGTH_UNPARSABLE_PATH,
                PYTHON_LENGTH_UNPARSABLE_SOURCE,
            ),
        ],
        PYTHON_LENGTH_UNPARSABLE_PATH,
        &[&expected],
    );
}

/// Where the file the run CAN judge stands, beside each item it cannot judge.
const PYTHON_LENGTH_JUDGED_PATH: &str = "judged.py";

/// Where the path the run cannot read stands inside the probe repository.
///
/// One name serves all three shapes: the same path holds no file, holds bytes
/// that are not UTF-8, or holds source nobody may read, so the way it refuses
/// is the one difference between the three probes.
const PYTHON_LENGTH_UNREADABLE_PATH: &str = "unreadable.py";

/// A Python file whose bytes are not UTF-8.
///
/// The declaration parses; the string literal holds two bytes that open no
/// UTF-8 sequence, so a reader opens the file and cannot decode it.
const PYTHON_LENGTH_UNDECODABLE_SOURCE: &[u8] = b"def short_function():\n    return '\xff\xfe'\n";

/// A Python file the tool could read if the mode let it.
///
/// The source is ordinary and stands under the gate, so a run that DID read it
/// would report no finding — which is the clean answer this rule must not give
/// for a file it never read.
const PYTHON_LENGTH_FORBIDDEN_SOURCE: &str = "def short_function():\n    return 1\n";

/// Holds the shipped Python function-length run to judging `judged.py` and to
/// stating the one path it could not read, through the real ruff pipeline.
///
/// The judged file carries one function over the gate, so the run has a finding
/// to lose. Losing it is what a nonzero exit over a declined item costs, and
/// staying silent about the path is what reads that path as a clean file.
fn verify_python_length_declines(path: &str, unreadable: &ShippedUnreadableFile) {
    let judged = python_procedure("long_procedure", OVER_THE_GATE_STATEMENTS);
    let expected = python_expected_row(PYTHON_LENGTH_JUDGED_PATH, &judged, "long_procedure");

    verify_unreadable_file_is_declined(
        PYTHON_PROJECT_TYPES,
        PYTHON_FUNCTION_LENGTH_RULE,
        &[(PYTHON_LENGTH_JUDGED_PATH, &judged)],
        path,
        unreadable,
        &[&expected],
    );
}

/// Acceptance: the shipped Python function-length tool rule DECLINES a path
/// that holds no file, through the real ruff pipeline.
///
/// Measured with ruff 0.14.5 over such a path, against the shipped command
/// line: `[]` on stdout, `warning: Failed to lint absent.py: No such file or
/// directory (os error 2)` on stderr, and exit 0. The status gate accepts 0, so
/// a script that read the report alone reported no finding and exited 0, and
/// the engine read a path ruff never opened as a clean file.
#[test]
fn the_shipped_python_function_length_tool_rule_declines_a_path_that_holds_no_file() {
    verify_python_length_declines(
        PYTHON_LENGTH_UNREADABLE_PATH,
        &ShippedUnreadableFile::Absent,
    );
}

/// Acceptance: the shipped Python function-length tool rule DECLINES a file
/// whose bytes are not UTF-8, through the real ruff pipeline.
///
/// Measured with ruff 0.14.5 over such a file, against the shipped command
/// line: `[]` on stdout, `warning: Failed to lint notutf8.py: stream did not
/// contain valid UTF-8` on stderr, and exit 0.
///
/// A readability test on the path admits this file — the mode lets the tool
/// open it — so the answer has to come from what ruff itself said.
#[test]
fn the_shipped_python_function_length_tool_rule_declines_a_file_it_cannot_decode() {
    verify_python_length_declines(
        PYTHON_LENGTH_UNREADABLE_PATH,
        &ShippedUnreadableFile::Undecodable(PYTHON_LENGTH_UNDECODABLE_SOURCE),
    );
}

/// Acceptance: the shipped Python function-length tool rule DECLINES a file it
/// may not read, through the real ruff pipeline.
///
/// Measured with ruff 0.14.5 over such a file, against the shipped command
/// line: `[]` on stdout, `warning: Failed to lint noread.py: Permission denied
/// (os error 13)` on stderr, and exit 0.
///
/// The probe takes every permission off the file, which is a mode, so it runs
/// on unix alone.
#[cfg(unix)]
#[test]
fn the_shipped_python_function_length_tool_rule_declines_a_file_it_may_not_read() {
    verify_python_length_declines(
        PYTHON_LENGTH_UNREADABLE_PATH,
        &ShippedUnreadableFile::Forbidden(PYTHON_LENGTH_FORBIDDEN_SOURCE),
    );
}
