//! Acceptance tests for the shipped `function-length-go` tool rule.
//!
//! Each test drives the SHIPPED script over a probe Go module and reads what
//! the real funlen reported.
//!
//! The gate is a STATEMENT count, so a probe of it runs to hundreds of lines:
//! a composite literal of 300 rows is one statement, and a function of 170
//! statements is 170 lines. No `&'static str` in this file could hold those
//! shapes, so each one is built at run time and driven through
//! [`verify_staged_rows_report`].

use super::*;

/// The statement gate the shipped rule states.
///
/// 250 code lines times 0.633, the measured median statements-per-line of the
/// procedural population of the corpus the rule body names.
const GO_STATEMENT_GATE: usize = 160;

/// The statement count of a probe function that must report: one over the
/// gate, plus a margin so a later toolchain that counts one statement
/// differently does not move the probe across the gate.
const OVER_THE_GATE_STATEMENTS: usize = GO_STATEMENT_GATE + 10;

/// How many statements of a procedure the head and the tail of its body take:
/// the `state := seed` that opens it and the `return state` that closes it.
const PROCEDURE_FRAME_STATEMENTS: usize = 2;

/// The row count of a probe data shape.
///
/// The shape must stand over the 250 code lines the `function-length` prompt
/// rule states, or it could not tell a line gate from a statement gate. Each
/// row is one line, and the shape carries a few lines of its own around them.
const DATA_SHAPE_ROWS: usize = 300;

/// The module manifest of a probe repository, as the work-list holds the path.
const GO_MODULE_MANIFEST_PATH: &str = "go.mod";

/// The module manifest of a probe repository.
///
/// golangci-lint loads packages rather than files, so a probe repository with
/// no manifest loads nothing. The `go` directive names an old release for the
/// reason the shipped `go.mod` fixture states: it is the lowest version the
/// probe needs, so the installed toolchain always satisfies it and never
/// downloads another one.
const GO_MODULE_MANIFEST: &str = "module function-length-probe\n\ngo 1.21\n";

/// The package clause every probe file opens with.
const GO_PACKAGE_CLAUSE: &str = "package probe\n\n";

/// The header `go generate` states above a generated file, and the blank line
/// under it.
///
/// The convention is one line that matches `^// Code generated .* DO NOT EDIT\.$`
/// above the first text that is neither a comment nor blank.
const GO_GENERATED_HEADER: &str = "// Code generated by protoc-gen-go. DO NOT EDIT.\n\n";

/// The declarations the data shapes of a probe file need: the row a composite
/// literal holds, and the builder an option chain returns.
const GO_PROBE_DECLARATIONS: &str = concat!(
    "type probeRow struct {\n\tname  string\n\tscore int\n}\n\n",
    "type probeBuilder struct {\n\toptions []int\n}\n\n",
    "func newProbeBuilder() *probeBuilder {\n\treturn &probeBuilder{}\n}\n\n",
    "func (b *probeBuilder) option(value int) *probeBuilder {\n",
    "\tb.options = append(b.options, value)\n\treturn b\n}\n\n",
);

/// A Go function of `statements` statements, one assignment for each step
/// between the seed and the return.
///
/// This is the shape the gate exists for: every line of it is a statement, so
/// its statement count and its line count are the same number.
fn go_procedure(name: &str, statements: usize) -> String {
    let mut source = format!("func {name}(seed uint64) uint64 {{\n\tstate := seed\n");
    for step in 0..statements - PROCEDURE_FRAME_STATEMENTS {
        source.push_str(&format!("\tstate = state*31 + {step}\n"));
    }
    source.push_str("\treturn state\n}\n\n");
    source
}

/// A Go function whose whole body is one composite literal of `rows` rows.
///
/// `function-length` exempts a function that is "mostly configuration/data".
/// The literal is ONE statement however many rows it holds.
fn go_data_table(name: &str, rows: usize) -> String {
    let mut source = format!("func {name}() []probeRow {{\n\treturn []probeRow{{\n");
    for row in 0..rows {
        source.push_str(&format!("\t\t{{name: \"row{row}\", score: {row}}},\n"));
    }
    source.push_str("\t}\n}\n\n");
    source
}

/// A Go function whose whole body is one builder chain of `options` options.
///
/// `function-length` names "builder patterns with many options" as its own
/// example of the data carve-out. The chain is ONE statement however many
/// options it sets.
fn go_option_builder(name: &str, options: usize) -> String {
    let mut source = format!("func {name}() *probeBuilder {{\n\treturn newProbeBuilder()");
    for option in 0..options {
        source.push_str(&format!(".\n\t\toption({option})"));
    }
    source.push_str("\n}\n\n");
    source
}

/// A Go table-driven test of `rows` cases: the table, the walk over it, and
/// one assertion inside the walk.
///
/// This is the idiomatic Go test shape, and it is data: the table is one
/// statement, so the whole test holds four however many rows it carries.
fn go_table_driven_test(name: &str, rows: usize) -> String {
    let mut source = format!("func {name}(t *testing.T) {{\n\tcases := []probeRow{{\n");
    for row in 0..rows {
        source.push_str(&format!("\t\t{{name: \"row{row}\", score: {row}}},\n"));
    }
    source.push_str(
        "\t}\n\tfor _, c := range cases {\n\t\tif c.score < 0 {\n\t\t\tt.Errorf(\"%s\", c.name)\n\t\t}\n\t}\n}\n\n",
    );
    source
}

/// A Go test function of `statements` statements, one log call for each step.
///
/// The name and the signature are the Go test convention at the DEFINITION,
/// which is the mark the test carve-out reads.
fn go_dense_test(name: &str, statements: usize) -> String {
    let mut source = format!("func {name}(t *testing.T) {{\n");
    for step in 0..statements {
        source.push_str(&format!("\tt.Log({step})\n"));
    }
    source.push_str("}\n\n");
    source
}

/// The head of the Go declaration of `name`, as the source writes it.
///
/// funlen anchors each finding on the line its `func` keyword stands on, so
/// this is the text [`declaration_line`] reads that line from.
fn go_declaration_head(name: &str) -> String {
    format!("func {name}(")
}

/// The `path:line` entry the run must report for the declaration of `name` in
/// `source`, staged at `path`.
fn go_expected_row(path: &str, source: &str, name: &str) -> String {
    expected_row(path, source, &go_declaration_head(name))
}

/// Where the file holding the three length shapes stands inside the probe
/// repository.
const GO_SHAPES_PATH: &str = "shapes/shapes.go";

/// Acceptance: the shipped Go function-length tool rule measures statements
/// and not lines, through the real funlen pipeline.
///
/// `function-length` exempts "Functions that are mostly configuration/data
/// (e.g., builder patterns with many options)". funlen holds two dimensions
/// and ORs them, so the exemption is expressible in one shape only: the
/// statement count is the gate, and the line limit stands out of reach.
///
/// The three functions of the probe hold the same file, so the shape is the
/// one difference between them. The procedure of 170 statements reports; the
/// composite literal of 300 rows and the builder chain of 300 options each
/// stand over 250 lines, hold one statement, and stay silent.
#[test]
fn the_shipped_go_function_length_tool_rule_measures_statements_and_not_lines() {
    let source = format!(
        "{GO_PACKAGE_CLAUSE}{GO_PROBE_DECLARATIONS}{}{}{}",
        go_procedure("LongProcedure", OVER_THE_GATE_STATEMENTS),
        go_data_table("DecisionTable", DATA_SHAPE_ROWS),
        go_option_builder("OptionBuilder", DATA_SHAPE_ROWS),
    );
    let expected = go_expected_row(GO_SHAPES_PATH, &source, "LongProcedure");

    verify_staged_rows_report(
        GO_PROJECT_TYPES,
        GO_FUNCTION_LENGTH_RULE,
        &[
            (GO_MODULE_MANIFEST_PATH, GO_MODULE_MANIFEST),
            (GO_SHAPES_PATH, &source),
        ],
        &[&expected],
        "the procedure stands over the statement gate, and the data table and the builder \
         chain each hold one statement over 300 lines",
    );
}

/// Where the test file of the carve-out probe stands inside the probe
/// repository.
const GO_SUITE_TEST_PATH: &str = "suite/suite_test.go";

/// Where the one file of the suite package that is not a test stands.
///
/// A directory holding a `_test.go` file alone is a package with no
/// non-test file, and `go list` states that rather than loading it. This file
/// makes the package.
const GO_SUITE_PATH: &str = "suite/suite.go";

/// Acceptance: the shipped Go function-length tool rule reads a test from its
/// DEFINITION, through the real funlen pipeline.
///
/// `function-length` exempts "Functions explicitly marked as tests", and
/// `cognitive-complexity` names the mark for the whole set: "Identify a test
/// from its attribute or framework naming convention at the definition, never
/// from the file name. A complex helper named `build_request` in a file called
/// `foo_test.rs` is still a complex function and is still listed."
///
/// funlen writes the function's own NAME into every message it reports, so the
/// exclusion rule reads the definition. The three declarations share one file,
/// so the name is the one difference between them: `TestTable` is data and
/// stands under the gate anyway, `TestDense` stands over the gate and is a
/// test by its name and signature, and `buildRequest` stands over the gate and
/// is a helper. The run must report the helper and no other.
#[test]
fn the_shipped_go_function_length_tool_rule_reads_a_test_from_its_definition() {
    let source = format!(
        "{}{GO_PROBE_DECLARATIONS}{}{}{}",
        "package probe\n\nimport \"testing\"\n\n",
        go_table_driven_test("TestTable", DATA_SHAPE_ROWS),
        go_dense_test("TestDense", OVER_THE_GATE_STATEMENTS),
        go_procedure("buildRequest", OVER_THE_GATE_STATEMENTS),
    );
    let expected = go_expected_row(GO_SUITE_TEST_PATH, &source, "buildRequest");

    verify_staged_rows_report(
        GO_PROJECT_TYPES,
        GO_FUNCTION_LENGTH_RULE,
        &[
            (GO_MODULE_MANIFEST_PATH, GO_MODULE_MANIFEST),
            (GO_SUITE_PATH, GO_PACKAGE_CLAUSE),
            (GO_SUITE_TEST_PATH, &source),
        ],
        &[&expected],
        "the helper reports because the carve-out reads the name at the definition; a run \
         that read the path alone would silence it beside the two tests",
    );
}

/// Where the plain position of the generated-code probe stands.
const GO_PLAIN_POSITION_PATH: &str = "plain/staged.go";

/// Where the generated position of the generated-code probe stands.
///
/// Neither position takes a path a generator is known by, so the path can
/// decide nothing and the header is the one difference between the two.
const GO_GENERATED_POSITION_PATH: &str = "marked/staged.go";

/// Drives the shipped script over a NEW probe repository holding one function
/// over the statement gate two times — in a plain file, and in a file whose
/// head carries the generated header — and holds the run to reporting the
/// plain position alone. `reason` states what the caller measures.
///
/// Each call stages a repository of its own and removes it when it returns, so
/// a caller that calls twice measures two workspaces holding the same bytes.
fn verify_the_generated_position_stays_silent(reason: &str) {
    let declarations = go_procedure("LongProcedure", OVER_THE_GATE_STATEMENTS);
    let plain = format!("{GO_PACKAGE_CLAUSE}{declarations}");
    let generated = format!("{GO_GENERATED_HEADER}{GO_PACKAGE_CLAUSE}{declarations}");
    let expected = go_expected_row(GO_PLAIN_POSITION_PATH, &plain, "LongProcedure");

    verify_staged_rows_report(
        GO_PROJECT_TYPES,
        GO_FUNCTION_LENGTH_RULE,
        &[
            (GO_MODULE_MANIFEST_PATH, GO_MODULE_MANIFEST),
            (GO_PLAIN_POSITION_PATH, &plain),
            (GO_GENERATED_POSITION_PATH, &generated),
        ],
        &[&expected],
        reason,
    );
}

/// Acceptance: the shipped Go function-length tool rule skips a generated
/// file, through the real funlen pipeline.
///
/// `function-length` exempts generated code, and golangci-lint makes that test
/// for itself: `linters.exclusions.generated` defaults to `lax`, which drops
/// every finding in a file whose head carries the `go generate` header.
///
/// The rule states `linters.exclusions.rules` for its test carve-out, and a
/// `rules` list does not replace the `generated` default. This test holds that:
/// the two positions carry the same function over the statement gate, and the
/// run must report the plain position alone.
#[test]
fn the_shipped_go_function_length_tool_rule_skips_a_generated_file() {
    verify_the_generated_position_stays_silent(
        "the plain file reports its function, and the file whose head carries the generated \
         header reports nothing",
    );
}

/// How many workspaces the cache probe drives, one after the other, over the
/// same bytes.
///
/// Two is the whole shape: the first workspace fills the cache and is gone
/// before the second one runs, which is what two checkouts of one repository,
/// and a review in a worktree, do every day.
const CACHE_PROBE_WORKSPACES: usize = 2;

/// Acceptance: the shipped Go function-length tool rule reads the workspace it
/// ran in, over bytes another workspace already cached.
///
/// golangci-lint answers by package CONTENT and stores each finding with the
/// ABSOLUTE path of the run that first cached it, so a shared cache hands a
/// second workspace the FIRST workspace's paths. Two things then break at
/// once: the engine drops a finding it cannot place in the workspace, and the
/// generated carve-out fails OPEN, because `linters.exclusions.generated`
/// reads the head of the file at the reported path and a path that is no
/// longer there lets the finding through.
///
/// The rule names a cache directory of its own for each workspace, so the two
/// runs of this test share no cached answer. Measured with golangci-lint
/// 2.12.2 over one shared cache and this probe: the second run reported the
/// first workspace's paths, and reported the generated position beside the
/// plain one once the first workspace was gone.
#[test]
fn the_shipped_go_function_length_tool_rule_reads_the_workspace_it_ran_in() {
    for _ in 0..CACHE_PROBE_WORKSPACES {
        verify_the_generated_position_stays_silent(
            "each workspace reports its own plain file and no other row; a run answering \
             from another workspace's cache reports that workspace's paths, and lets the \
             generated position through",
        );
    }
}

/// How many runs of the shipped script the lock probe starts together.
///
/// golangci-lint takes ONE file lock, and the lock stands in the cache
/// directory the run reads — which the shipped script names for the workspace,
/// so the runs of one workspace share it. Measured over this probe without the
/// `allow-serial-runners` key, three rounds from a cold cache and three from a
/// warm one: 0 of 4 runs started together reported nothing, and 3 of 8 reported
/// nothing, in each of the six rounds. Four runs never clash, so the probe
/// needs eight.
const LOCK_PROBE_RUNS: usize = 8;

/// The run the lock probe drives: the shipped Go function-length rule over a
/// Go workspace.
///
/// The run states no `expected`, because the probe compares the runs against
/// each other rather than against a list this constant holds.
const GO_FUNCTION_LENGTH_LOCK_RUN: ShippedRun = ShippedRun {
    project_types: GO_PROJECT_TYPES,
    rule: GO_FUNCTION_LENGTH_RULE,
    expected: NO_FINDINGS,
};

/// Acceptance: the shipped Go function-length tool rule reports while another
/// instance holds the lock, through the real funlen pipeline.
///
/// `run: allow-serial-runners: true` makes a second instance WAIT for the
/// lock. Without the key it stops with `Error: parallel golangci-lint is
/// running` on stderr and writes nothing to stdout, and the script drops
/// stderr — so the run reads as a clean file rather than as a failure, and the
/// review is told the code is clean by a run that judged nothing.
///
/// Measured with golangci-lint 2.12.2 over this probe, three rounds from a
/// cold cache and three from a warm one: without the key 3 of 8 runs reported
/// nothing in each of the six rounds, and the same runs with stderr kept
/// carried the lock error on each of those three. With the key all eight
/// reported the one finding, in each of the six rounds.
#[test]
fn the_shipped_go_function_length_tool_rule_reports_while_another_run_holds_the_lock() {
    let source = format!(
        "{GO_PACKAGE_CLAUSE}{}",
        go_procedure("LongProcedure", OVER_THE_GATE_STATEMENTS)
    );
    let expected = sorted_names(&[go_expected_row(GO_SHAPES_PATH, &source, "LongProcedure")]);

    let reported = rows_of_runs_started_together(
        &GO_FUNCTION_LENGTH_LOCK_RUN,
        &[
            (GO_MODULE_MANIFEST_PATH, GO_MODULE_MANIFEST),
            (GO_SHAPES_PATH, &source),
        ],
        NO_SCRIPT_FILES,
        LOCK_PROBE_RUNS,
    );

    assert!(
        reported.iter().all(|run| *run == expected),
        "every run started together must report {expected:?}, because a second instance \
         waits for the lock rather than stopping; a run that stopped wrote its reason to \
         the stderr the script drops and reads here as a clean file: {reported:?}"
    );
}
