//! End-to-end integration test for the SDK's **operation-tool `_meta` path
//! sugar**, driven through a real plugin.
//!
//! This is the capability-level companion to `sdk.rs`. Where `sdk.rs` drives
//! the dispatch Proxy with a hand-built recording `HostDispatcher` and a canned
//! `_meta` tree, this test proves the same `_meta` round-trip works when a
//! *real plugin* — discovered from disk and run in a real V8 isolate — calls a
//! *real operation tool* whose `_meta` was generated by the production schema
//! machinery.
//!
//! It follows the reference shape of `files_dispatch_e2e.rs`: a real V8
//! isolate, a real registered server, and an effect observed on disk that can
//! only happen if every stage works.
//!
//! # Why the `files` tool is the operation tool under test
//!
//! The unified `files` tool is a genuine in-process MCP *operation tool*: its
//! `tools/list` definition carries an `io.swissarmyhammer/operations` `_meta`
//! tree keyed by noun (`file`) and verb (`read`, `write`, `edit`, …), with each
//! leaf's `op` being the canonical `"<verb> <noun>"` selector — `"write file"`,
//! `"read file"`. `plugin_module_exposure_test.rs` already asserts the exposed
//! `files` tool publishes that `_meta`. So the `files` tool is the real
//! operation tool this test needs, obtained through the same
//! [`McpServer::expose_tools_to_plugin_host`] path the production MCP bootstrap
//! uses — no mock, no hand-built `_meta`.
//!
//! # What a passing run proves
//!
//! The probe plugin's `load()` exercises the SDK's operation-tool dispatch all
//! three ways the SDK supports, against the real `files` operation tool:
//!
//! 1. **Path form** — `this.fs.files.file.write({ file_path, content })`. The
//!    SDK has no `op` in `args`; it must read the tool's
//!    `_meta["io.swissarmyhammer/operations"]["file"]["write"].op`, find
//!    `"write file"`, and dispatch `tools/call("files", { op: "write file",
//!    … })`. The probe file landing on disk can *only* happen if the SDK read
//!    `_meta` and built that `op` string from the `file.write` path.
//! 2. **Direct form** — `this.fs.files({ op: "read file", path })`. The `op` is
//!    already in `args`; the SDK passes it straight through. The plugin reads
//!    the first probe file back, proving the direct form reached the handler.
//! 3. **Unknown verb path** — `this.fs.files.file.destroy({ … })`. The `file`
//!    noun has no `destroy` verb in `_meta`, so the SDK must raise
//!    `UnknownOperation` *before* any `tools/call`. The plugin catches it and
//!    records the error name into a third file.
//!
//! Three assertions observe the filesystem — the only honest verification for
//! an in-process server whose state *is* the filesystem:
//!
//! - the path-form file exists with the written payload — the `_meta` lookup
//!   produced `op: "write file"`;
//! - the direct-form file exists holding the read-back content — the direct
//!   form reached the real `read file` handler and its result round-tripped;
//! - the unknown-verb file holds exactly `UnknownOperation` — the SDK rejected
//!   the bad path from `_meta` rather than dispatching a phantom `tools/call`.
//!
//! If the SDK's `_meta` resolution is broken at any stage — the path form
//! fails to build the `op`, or the unknown verb is not rejected — at least one
//! assertion fails.
//!
//! # Isolation
//!
//! The test owns its own [`tempfile::TempDir`] roots and a fresh
//! [`PluginHost`]; nothing is `static` and no temp dir is reused. Every
//! cross-thread interaction is bounded by a timeout so a wedged isolate fails
//! the test fast instead of hanging CI.

use std::path::Path;
use std::time::Duration;

use swissarmyhammer_directory::SwissarmyhammerConfig;
use swissarmyhammer_plugin::PluginHost;
use swissarmyhammer_prompts::PromptLibrary;
use swissarmyhammer_tools::mcp::McpServer;

/// A generous upper bound on any single host or server interaction.
///
/// Building the MCP server stands up the full in-process tool registry, so the
/// bound is wider than a bare isolate test would need.
const TIMEOUT: Duration = Duration::from_secs(60);

/// The file the plugin writes through the **path form**
/// (`this.fs.files.file.write`) — proof the SDK read `_meta` and built the
/// `"write file"` op from the `file.write` path.
const PATH_FORM_FILE: &str = "path_form_probe.txt";

/// The file the plugin writes after reading the path-form file back through
/// the **direct form** (`this.fs.files({ op: "read file", … })`) — proof the
/// direct form reached the real `read file` handler and its result
/// round-tripped into the isolate.
const DIRECT_FORM_FILE: &str = "direct_form_probe.txt";

/// The file the plugin writes the *name* of the error raised by an **unknown
/// verb path** into — proof the SDK rejected `file.destroy` from `_meta`
/// instead of dispatching a phantom `tools/call`.
const UNKNOWN_VERB_FILE: &str = "unknown_verb_probe.txt";

/// The exact payload the plugin writes via the path form and then reads back.
/// It is asserted verbatim in both the path-form and direct-form files.
const PROBE_PAYLOAD: &str = "e2e payload routed through operation _meta path sugar";

/// Builds a real MCP server against an isolated temp working directory.
///
/// The temp `work_dir` keeps the server's bootstrap from walking the real
/// monorepo. `agent_mode` is `true` so the full in-process tool set — including
/// the unified `files` tool, the operation tool under test — is registered,
/// which is what makes the real `files` operation tool reachable for exposure.
async fn build_mcp_server(work_dir: &Path) -> McpServer {
    McpServer::new_with_work_dir(PromptLibrary::new(), work_dir.to_path_buf(), None, true)
        .await
        .expect("MCP server bootstrap should succeed")
}

/// Encodes `value` as a JSON/TypeScript string literal, quotes included.
///
/// Used to interpolate filesystem paths into the generated entry module;
/// `serde_json` handles escaping of backslashes and quotes so a Windows path or
/// a path with unusual characters still produces valid source.
fn json_string(value: &str) -> String {
    serde_json::to_string(value).expect("a string always serializes to JSON")
}

/// Writes the probe plugin bundle — a real `plugin.json` plus a real entry
/// `.ts` — into `<project_root>/plugins/probe/`.
///
/// The manifest declares the single server name the plugin `provides` (`fs`);
/// the host rejects any `register` of a name absent from this list.
///
/// The entry module's `load()` activates the host-exposed real `files`
/// operation tool under the name `fs`, then drives the SDK's operation-tool
/// dispatch three ways:
///
/// 1. path form — `this.fs.files.file.write(...)`, the `_meta` round-trip;
/// 2. direct form — `this.fs.files({ op: "read file", ... })`;
/// 3. an unknown verb path — `this.fs.files.file.destroy(...)`, caught.
///
/// The probe file paths are absolute literals the test owns (it owns the temp
/// directory), interpolated into the TypeScript source; the calls themselves
/// still cross the entire real pipeline.
fn write_probe_plugin(project_root: &Path, output_dir: &Path) {
    let plugin_dir = project_root
        .join(swissarmyhammer_plugin::PLUGINS_SUBDIR)
        .join("probe");
    std::fs::create_dir_all(&plugin_dir).expect("probe plugin directory should be created");

    // A real manifest. `provides` lists exactly the one server name the
    // plugin's `load()` registers.
    let manifest = "{\n  \
         \"id\": \"probe\",\n  \
         \"name\": \"operation meta probe\",\n  \
         \"version\": \"1.0.0\",\n  \
         \"entry\": \"entry.ts\",\n  \
         \"provides\": [\"fs\"]\n}\n";
    std::fs::write(plugin_dir.join("plugin.json"), manifest)
        .expect("probe plugin.json should be written");

    let path_form_path = output_dir.join(PATH_FORM_FILE);
    let direct_form_path = output_dir.join(DIRECT_FORM_FILE);
    let unknown_verb_path = output_dir.join(UNKNOWN_VERB_FILE);

    // The entry module. `load()` uses ONLY the registered `files` operation
    // tool, and exercises the SDK's three operation-dispatch shapes:
    //
    //   1. `this.fs.files.file.write(...)` — PATH FORM. No `op` in args; the
    //      SDK must read `_meta["io.swissarmyhammer/operations"]["file"]
    //      ["write"].op` to produce `op: "write file"`. The first file lands
    //      only if that lookup worked.
    //   2. `this.fs.files({ op: "read file", ... })` — DIRECT FORM. `op` is
    //      already present; it crosses verbatim. The read result returns as a
    //      `CallToolResult` shape and is written into the second file.
    //   3. `this.fs.files.file.destroy(...)` — UNKNOWN VERB. `file` has no
    //      `destroy` verb in `_meta`; the SDK must raise `UnknownOperation`
    //      before any `tools/call`. The error name is written into the third
    //      file via the (proven-working) path form.
    //
    // A non-trivial check on the read-back value makes the plugin fail loudly
    // if return-value marshalling is broken, rather than silently writing an
    // empty second file.
    let entry = format!(
        "import {{ Plugin, makePluginThis }} from '@swissarmyhammer/plugin';\n\
         \n\
         /** Extracts the file text from a `files` `read file` result. */\n\
         function readBackText(result: unknown): string {{\n\
         \x20 const content = (result as {{ content?: Array<{{ text?: string }}> }}).content;\n\
         \x20 if (content === undefined || content.length === 0) {{\n\
         \x20   throw new Error('read file result carried no content');\n\
         \x20 }}\n\
         \x20 const text = content[0].text;\n\
         \x20 if (typeof text !== 'string') {{\n\
         \x20   throw new Error('read file content[0].text was not a string');\n\
         \x20 }}\n\
         \x20 return text;\n\
         }}\n\
         \n\
         class ProbePlugin extends Plugin {{\n\
         \x20 async load(): Promise<void> {{\n\
         \x20   // Activate the host-exposed real `files` operation tool as `fs`.\n\
         \x20   this.register('fs', {{ rust: 'files' }});\n\
         \n\
         \x20   // (1) PATH FORM: `this.fs.files.file.write` carries no `op`; the\n\
         \x20   //     SDK must read `_meta` and build `op: \"write file\"` from\n\
         \x20   //     the `file.write` path.\n\
         \x20   await this.fs.files.file.write({{\n\
         \x20     file_path: {path_form},\n\
         \x20     content: {payload},\n\
         \x20   }});\n\
         \n\
         \x20   // (2) DIRECT FORM: `op` is already in args; it crosses verbatim.\n\
         \x20   const readResult = await this.fs.files({{\n\
         \x20     op: 'read file',\n\
         \x20     path: {path_form},\n\
         \x20   }});\n\
         \x20   const readBack = readBackText(readResult);\n\
         \x20   if (readBack.indexOf({payload}) < 0) {{\n\
         \x20     throw new Error('read file did not return the written payload');\n\
         \x20   }}\n\
         \x20   await this.fs.files.file.write({{\n\
         \x20     file_path: {direct_form},\n\
         \x20     content: readBack,\n\
         \x20   }});\n\
         \n\
         \x20   // (3) UNKNOWN VERB: `file` has no `destroy` verb in `_meta`; the\n\
         \x20   //     SDK must raise `UnknownOperation` before any `tools/call`.\n\
         \x20   let unknownName = 'no-error';\n\
         \x20   try {{\n\
         \x20     await this.fs.files.file.destroy({{ path: {path_form} }});\n\
         \x20   }} catch (error) {{\n\
         \x20     unknownName = (error as Error).name;\n\
         \x20   }}\n\
         \x20   await this.fs.files.file.write({{\n\
         \x20     file_path: {unknown_verb},\n\
         \x20     content: unknownName,\n\
         \x20   }});\n\
         \x20 }}\n\
         }}\n\
         \n\
         export async function load(): Promise<unknown> {{\n\
         \x20 const p = makePluginThis(new ProbePlugin()) as ProbePlugin;\n\
         \x20 await p.load();\n\
         \x20 return null;\n\
         }}\n",
        path_form = json_string(&path_form_path.to_string_lossy()),
        direct_form = json_string(&direct_form_path.to_string_lossy()),
        unknown_verb = json_string(&unknown_verb_path.to_string_lossy()),
        payload = json_string(PROBE_PAYLOAD),
    );
    std::fs::write(plugin_dir.join("entry.ts"), entry).expect("probe entry.ts should be written");
}

/// A discovered probe plugin drives the real `files` operation tool through
/// the SDK's `_meta` path sugar, the direct form, and an unknown verb path.
///
/// This single test stitches the operation-`_meta` round-trip together end to
/// end:
///
/// - the real `files` operation tool — carrying its
///   `io.swissarmyhammer/operations` `_meta` — is built by the MCP server
///   bootstrap and exposed to the host with
///   [`McpServer::expose_tools_to_plugin_host`]; no mock, no hand-built `_meta`;
/// - the probe bundle (`plugin.json` + `entry.ts`) is discovered and loaded
///   through `discover_and_load_all`, which transpiles the TypeScript, creates
///   a fresh V8 isolate, and runs the exported `load`;
/// - inside the isolate the SDK reads the operation tool's `_meta` to turn a
///   `file.write` path into `tools/call("files", { op: "write file", … })`,
///   passes a direct-form `op` through verbatim, and raises `UnknownOperation`
///   for a `file.destroy` path the `_meta` does not describe.
#[tokio::test]
async fn discovered_plugin_drives_operation_meta_path_sugar_end_to_end() {
    // Per-test isolation: every root is this test's own `TempDir`.
    let work_dir = tempfile::TempDir::new().expect("work dir temp");
    let project_root = tempfile::TempDir::new().expect("project plugin root temp");
    let output_dir = tempfile::TempDir::new().expect("probe output temp");

    // The probe bundle is laid out under the project layer's `plugins/` dir,
    // where discovery will find it.
    write_probe_plugin(project_root.path(), output_dir.path());

    // The real in-process tool set, including the unified `files` operation
    // tool whose `_meta` is the subject of this test.
    let server = build_mcp_server(work_dir.path()).await;

    // A fresh host, with the project layer pointed at the temp plugin root.
    let host = PluginHost::for_tests(
        work_dir.path().to_path_buf(),
        Some(project_root.path().to_path_buf()),
    );

    // Expose every in-process tool — `files` among them — as an addressable
    // Rust module. This is the production exposure path: each tool is wrapped
    // in a `ToolModuleServer` and recorded in the host's available-modules
    // table. No module is live until a plugin activates it.
    tokio::time::timeout(TIMEOUT, server.expose_tools_to_plugin_host(&host))
        .await
        .expect("exposing the in-process tools should not hang")
        .expect("exposing the in-process tools should succeed");

    // Trigger discovery: the host scans the project layer, transpiles the
    // probe's `entry.ts`, creates a fresh isolate, and runs the exported
    // `load` — whose body exercises the operation-`_meta` dispatch three ways.
    let loaded = tokio::time::timeout(
        TIMEOUT,
        host.discover_and_load_all::<SwissarmyhammerConfig>(),
    )
    .await
    .expect("discovery should not hang")
    .expect("discovering and loading the probe plugin should succeed");
    assert_eq!(
        loaded.len(),
        1,
        "exactly the one probe plugin should be discovered and loaded"
    );

    // Assertion 1 — the path-form file exists with the written payload. This
    // can *only* be true if `this.fs.files.file.write(...)` made the SDK read
    // the operation tool's `_meta`, find `["file"]["write"].op == "write
    // file"`, and dispatch `tools/call("files", { op: "write file", … })`. A
    // broken `_meta` lookup would raise `UnknownOperation` and fail `load()`
    // before this file was ever written.
    let path_form_path = output_dir.path().join(PATH_FORM_FILE);
    let path_form_content = std::fs::read_to_string(&path_form_path).unwrap_or_else(|error| {
        panic!(
            "the path-form probe file must exist at {} — the SDK did not read \
             `_meta` and build the `write file` op from the `file.write` path: \
             {error}",
            path_form_path.display()
        )
    });
    assert_eq!(
        path_form_content, PROBE_PAYLOAD,
        "the path-form probe file must hold exactly the payload the plugin \
         wrote — proving the `_meta` path sugar produced `op: \"write file\"`"
    );

    // Assertion 2 — the direct-form file exists holding the read-back content.
    // The plugin read the path-form file back with the direct form
    // (`{ op: "read file", … }`) and wrote the *read-back* string here, so this
    // proves the direct-form `op` crossed verbatim into the real `read file`
    // handler and the result round-tripped into the isolate.
    let direct_form_path = output_dir.path().join(DIRECT_FORM_FILE);
    let direct_form_content = std::fs::read_to_string(&direct_form_path).unwrap_or_else(|error| {
        panic!(
            "the direct-form probe file must exist at {} — the direct-form \
             `read file` call did not round-trip: {error}",
            direct_form_path.display()
        )
    });
    assert_eq!(
        direct_form_content, PROBE_PAYLOAD,
        "the direct-form probe file must hold the content the plugin read back \
         — proving the direct form `{{ op: \"read file\" }}` reached the handler"
    );

    // Assertion 3 — the unknown-verb file holds exactly `UnknownOperation`.
    // `this.fs.files.file.destroy(...)` names a verb the `files` operation
    // tool's `_meta` does not describe, so the SDK must reject the path with
    // `UnknownOperation` *before* issuing any `tools/call`. The plugin caught
    // that error and wrote its `name` here.
    let unknown_verb_path = output_dir.path().join(UNKNOWN_VERB_FILE);
    let unknown_verb_content =
        std::fs::read_to_string(&unknown_verb_path).unwrap_or_else(|error| {
            panic!(
                "the unknown-verb probe file must exist at {}: {error}",
                unknown_verb_path.display()
            )
        });
    assert_eq!(
        unknown_verb_content, "UnknownOperation",
        "an unknown verb path must raise `UnknownOperation` — the SDK must \
         reject a noun/verb its `_meta` does not describe, not dispatch it"
    );
}
