//! Spatial focus state: entry registry, layer stack, focused key tracking, and event emission.
//!
//! Thread-safe via internal `RwLock`. Mutation methods return `Option<FocusChanged>`
//! so the caller (Tauri layer) can emit events only when focus actually changed.
//! This module knows nothing about Tauri — it is a pure state machine.

use std::collections::HashMap;
use std::sync::RwLock;

use serde::{Deserialize, Serialize};

/// Event payload emitted when the focused spatial key changes.
///
/// Both fields are optional: `prev_key` is `None` when nothing was focused,
/// `next_key` is `None` when focus is cleared (e.g. the focused entry was
/// unregistered).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct FocusChanged {
    /// The spatial key that lost focus, or `None` if nothing was focused.
    pub prev_key: Option<String>,
    /// The spatial key that gained focus, or `None` if focus was cleared.
    pub next_key: Option<String>,
}

/// Axis-aligned bounding rectangle for spatial navigation scoring.
///
/// Coordinates are in logical pixels relative to the viewport origin.
/// All fields use `f64` to match DOM `getBoundingClientRect()` values.
/// The default is a zero-origin, zero-sized rect (`x=0, y=0, width=0, height=0`).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Rect {
    /// Left edge x-coordinate.
    pub x: f64,
    /// Top edge y-coordinate.
    pub y: f64,
    /// Width in logical pixels.
    pub width: f64,
    /// Height in logical pixels.
    pub height: f64,
}

impl Rect {
    /// Right edge: `x + width`.
    pub fn right(&self) -> f64 {
        self.x + self.width
    }

    /// Bottom edge: `y + height`.
    pub fn bottom(&self) -> f64 {
        self.y + self.height
    }
}

/// A registered spatial entry — one per FocusScope mount.
///
/// Keyed by `key` (ULID generated client-side). The same moniker can
/// appear in multiple entries (e.g. a task card on the board and a
/// mention pill in the inspector).
#[derive(Debug, Clone, PartialEq)]
pub struct SpatialEntry {
    /// Unique spatial key (ULID generated by React on mount).
    pub key: String,
    /// Entity moniker (e.g. `"task:01ABC"`, `"field:task:01ABC.title"`).
    pub moniker: String,
    /// Bounding rectangle in viewport coordinates.
    pub rect: Rect,
    /// Spatial key of the FocusLayer this scope lives in.
    pub layer_key: String,
    /// Optional parent scope key for container-first navigation.
    ///
    /// When set, `navigate()` searches siblings in the same parent scope
    /// before falling back to the full layer.
    pub parent_scope: Option<String>,
    /// Directional navigation overrides.
    ///
    /// Key is a direction string (e.g. `"Right"`, `"Up"`). Value is
    /// `Some(moniker)` to redirect navigation to that moniker, or `None`
    /// to block navigation in that direction. Missing keys fall through
    /// to spatial navigation.
    pub overrides: HashMap<String, Option<String>>,
}

/// A batch registration entry — same fields as `register()` but collected
/// into a `Vec` for `register_batch()` to avoid per-entry lock overhead.
#[derive(Debug, Clone)]
pub struct BatchEntry {
    /// Unique spatial key (ULID generated by React on mount).
    pub key: String,
    /// Entity moniker (e.g. `"task:01ABC"`, `"field:task:01ABC.title"`).
    pub moniker: String,
    /// Bounding rectangle in viewport coordinates.
    pub rect: Rect,
    /// Spatial key of the FocusLayer this scope lives in.
    pub layer_key: String,
    /// Optional parent scope key for container-first navigation.
    pub parent_scope: Option<String>,
    /// Directional navigation overrides.
    pub overrides: HashMap<String, Option<String>>,
}

/// A focus layer entry in the layer stack.
///
/// Layers are hard navigation boundaries — `navigate()` only considers
/// entries in the active (topmost) layer.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LayerEntry {
    /// Unique layer key (ULID generated by React on mount).
    pub key: String,
    /// Human-readable layer name (e.g. `"window"`, `"inspector"`).
    pub name: String,
    /// Focus memory: the last focused key before this layer lost focus.
    ///
    /// Saved when `focus()` changes the focused key — the old key is stored
    /// as `last_focused` on the active layer. When `remove_layer()` pops a
    /// layer, focus restores to the layer below's `last_focused`.
    pub last_focused: Option<String>,
}

/// Ordered layer stack with arbitrary removal by key.
///
/// The topmost entry is the active layer. `remove` by key (not pop)
/// handles out-of-order unmount: if inspector A opens, then dialog B
/// opens on top, then A closes — `remove(A.key)` works correctly and
/// B remains active.
#[derive(Debug, Default)]
pub struct LayerStack {
    layers: Vec<LayerEntry>,
}

impl LayerStack {
    /// Push a new layer onto the top of the stack.
    pub fn push(&mut self, key: String, name: String) {
        self.layers.push(LayerEntry {
            key,
            name,
            last_focused: None,
        });
    }

    /// Remove a layer by key. Returns `true` if found and removed.
    pub fn remove(&mut self, key: &str) -> bool {
        let before = self.layers.len();
        self.layers.retain(|l| l.key != key);
        self.layers.len() < before
    }

    /// Returns the active (topmost) layer, or `None` if the stack is empty.
    pub fn active(&self) -> Option<&LayerEntry> {
        self.layers.last()
    }

    /// Returns a mutable reference to the active (topmost) layer.
    pub fn active_mut(&mut self) -> Option<&mut LayerEntry> {
        self.layers.last_mut()
    }

    /// Find a layer by key and return a mutable reference.
    pub fn find_mut(&mut self, key: &str) -> Option<&mut LayerEntry> {
        self.layers.iter_mut().find(|l| l.key == key)
    }

    /// Returns `true` if the stack is empty.
    pub fn is_empty(&self) -> bool {
        self.layers.is_empty()
    }

    /// Returns the number of layers in the stack.
    pub fn len(&self) -> usize {
        self.layers.len()
    }
}

/// Spatial focus state machine: entry registry, layer stack, and focused key.
///
/// Thread-safe via internal `RwLock`. All mutation methods return
/// `Option<FocusChanged>` — `Some` when the focus actually changed (the
/// caller should emit the event), `None` when the mutation was a no-op.
pub struct SpatialState {
    inner: RwLock<SpatialStateInner>,
}

#[derive(Debug, Default)]
struct SpatialStateInner {
    /// Registered spatial entries keyed by spatial key (ULID).
    entries: HashMap<String, SpatialEntry>,
    /// The currently focused spatial key, or `None`.
    focused_key: Option<String>,
    /// Ordered layer stack — topmost is active.
    layer_stack: LayerStack,
}

impl SpatialStateInner {
    /// Save the outgoing focused key as `last_focused` on the layer that
    /// owns it. Called before updating `focused_key` so the old layer
    /// remembers what was focused in it.
    fn save_focus_memory(&mut self, prev_key: &str) {
        if let Some(entry) = self.entries.get(prev_key) {
            let owner = entry.layer_key.clone();
            if let Some(layer) = self.layer_stack.find_mut(&owner) {
                layer.last_focused = Some(prev_key.to_string());
            }
        }
    }
}

impl SpatialState {
    /// Create an empty spatial state with no entries, no focus, and no layers.
    pub fn new() -> Self {
        Self {
            inner: RwLock::new(SpatialStateInner::default()),
        }
    }

    /// Register a spatial entry with its bounding rect, layer key, optional
    /// parent scope, and directional overrides.
    ///
    /// Overwrites any existing entry with the same key. The `parent_scope`
    /// enables container-first navigation — entries with the same scope are
    /// searched before the full layer. The `overrides` map allows
    /// per-entry navigation redirection or blocking.
    pub fn register(
        &self,
        key: String,
        moniker: String,
        rect: Rect,
        layer_key: String,
        parent_scope: Option<String>,
        overrides: HashMap<String, Option<String>>,
    ) {
        let mut inner = self.inner.write().unwrap();
        inner.entries.insert(
            key.clone(),
            SpatialEntry {
                key,
                moniker,
                rect,
                layer_key,
                parent_scope,
                overrides,
            },
        );
    }

    /// Register multiple spatial entries in a single lock acquisition.
    ///
    /// Each entry overwrites any existing entry with the same key (upsert
    /// semantics, same as `register`). Use this for batch operations like
    /// virtualizer placeholder registration to avoid per-entry lock overhead.
    pub fn register_batch(&self, entries: Vec<BatchEntry>) {
        let mut inner = self.inner.write().unwrap();
        for e in entries {
            inner.entries.insert(
                e.key.clone(),
                SpatialEntry {
                    key: e.key,
                    moniker: e.moniker,
                    rect: e.rect,
                    layer_key: e.layer_key,
                    parent_scope: e.parent_scope,
                    overrides: e.overrides,
                },
            );
        }
    }

    /// Unregister multiple spatial entries in a single lock acquisition.
    ///
    /// For each key, if it was the focused key, focus is cleared. Returns
    /// a `FocusChanged` event if the focused key was among those removed.
    pub fn unregister_batch(&self, keys: &[String]) -> Option<FocusChanged> {
        let mut inner = self.inner.write().unwrap();
        let mut lost_focus = false;
        for key in keys {
            inner.entries.remove(key);
            if inner.focused_key.as_deref() == Some(key.as_str()) {
                lost_focus = true;
            }
        }
        if lost_focus {
            let prev = inner.focused_key.take();
            Some(FocusChanged {
                prev_key: prev,
                next_key: None,
            })
        } else {
            None
        }
    }

    /// Update the bounding rect of an existing entry.
    /// No-op if the key is not registered.
    pub fn update_rect(&self, key: &str, rect: Rect) {
        let mut inner = self.inner.write().unwrap();
        if let Some(entry) = inner.entries.get_mut(key) {
            entry.rect = rect;
        }
    }

    /// Unregister a spatial entry by key.
    ///
    /// If the removed entry was the focused key, focus is cleared and a
    /// `FocusChanged` event is returned. Otherwise returns `None`.
    pub fn unregister(&self, key: &str) -> Option<FocusChanged> {
        let mut inner = self.inner.write().unwrap();
        inner.entries.remove(key);
        if inner.focused_key.as_deref() == Some(key) {
            let prev = inner.focused_key.take();
            Some(FocusChanged {
                prev_key: prev,
                next_key: None,
            })
        } else {
            None
        }
    }

    /// Set focus to a spatial key. Returns `Some(FocusChanged)` if focus
    /// actually changed, `None` if the key was already focused or is not
    /// registered. Saves the outgoing focused key as `last_focused` on the
    /// active layer for focus memory.
    pub fn focus(&self, key: &str) -> Option<FocusChanged> {
        let mut inner = self.inner.write().unwrap();
        if inner.focused_key.as_deref() == Some(key) {
            return None;
        }
        if !inner.entries.contains_key(key) {
            return None;
        }
        let prev = inner.focused_key.take();
        if let Some(ref pk) = prev {
            inner.save_focus_memory(pk);
        }
        inner.focused_key = Some(key.to_string());
        Some(FocusChanged {
            prev_key: prev,
            next_key: Some(key.to_string()),
        })
    }

    /// Clear focus without removing any entry. Returns `Some(FocusChanged)`
    /// if something was focused, `None` if already unfocused.
    pub fn clear_focus(&self) -> Option<FocusChanged> {
        let mut inner = self.inner.write().unwrap();
        let prev = inner.focused_key.take();
        prev.map(|p| FocusChanged {
            prev_key: Some(p),
            next_key: None,
        })
    }

    /// Returns the currently focused spatial key, or `None`.
    pub fn focused_key(&self) -> Option<String> {
        self.inner.read().unwrap().focused_key.clone()
    }

    /// Look up a registered entry by spatial key.
    pub fn get(&self, key: &str) -> Option<SpatialEntry> {
        self.inner.read().unwrap().entries.get(key).cloned()
    }

    /// Returns the number of registered entries.
    pub fn len(&self) -> usize {
        self.inner.read().unwrap().entries.len()
    }

    /// Returns `true` if no entries are registered.
    pub fn is_empty(&self) -> bool {
        self.inner.read().unwrap().entries.is_empty()
    }

    /// Push a focus layer onto the layer stack.
    pub fn push_layer(&self, key: String, name: String) {
        let mut inner = self.inner.write().unwrap();
        inner.layer_stack.push(key, name);
    }

    /// Remove a focus layer by key.
    ///
    /// If the layer below has a `last_focused` key that is still registered,
    /// focus is restored to it and a `FocusChanged` event is returned.
    pub fn remove_layer(&self, key: &str) -> Option<FocusChanged> {
        let mut inner = self.inner.write().unwrap();
        if !inner.layer_stack.remove(key) {
            return None;
        }
        // Restore focus from the layer now on top (if it has last_focused).
        let restore_key = inner
            .layer_stack
            .active()
            .and_then(|l| l.last_focused.clone());
        if let Some(ref rk) = restore_key {
            if inner.entries.contains_key(rk.as_str()) {
                let prev = inner.focused_key.take();
                inner.focused_key = Some(rk.clone());
                return Some(FocusChanged {
                    prev_key: prev,
                    next_key: Some(rk.clone()),
                });
            }
        }
        None
    }

    /// Returns the active (topmost) layer key and name, or `None`.
    pub fn active_layer(&self) -> Option<LayerEntry> {
        self.inner.read().unwrap().layer_stack.active().cloned()
    }

    /// Returns the number of layers in the stack.
    pub fn layer_count(&self) -> usize {
        self.inner.read().unwrap().layer_stack.len()
    }

    /// Return a snapshot of every registered spatial entry.
    ///
    /// Intended for test infrastructure and debug tooling (for example, the
    /// `__spatial_dump` Tauri command in `kanban-app`) that needs to inspect
    /// the full registry without poking at internals. The ordering of the
    /// returned vector is unspecified — consumers that need deterministic
    /// order should sort by the fields they care about.
    pub fn entries_snapshot(&self) -> Vec<SpatialEntry> {
        self.inner
            .read()
            .unwrap()
            .entries
            .values()
            .cloned()
            .collect()
    }

    /// Return a snapshot of the layer stack, bottom-first.
    ///
    /// The last element is the active (topmost) layer. Like
    /// [`entries_snapshot`], this is a debug/test accessor that avoids the
    /// need for callers to reach into the internal `LayerStack`.
    ///
    /// [`entries_snapshot`]: Self::entries_snapshot
    pub fn layers_snapshot(&self) -> Vec<LayerEntry> {
        self.inner.read().unwrap().layer_stack.layers.clone()
    }

    /// Navigate from the focused entry in a direction.
    ///
    /// Checks the source entry's override map first:
    /// - `Some(Some(moniker))` — redirect to the entry with that moniker
    /// - `Some(None)` — block navigation (return `Ok(None)`)
    /// - `None` — fall through to spatial beam test
    ///
    /// For spatial fallback, filters to entries in the active layer, runs
    /// container-first search (same parent_scope siblings first, then full
    /// layer), and updates `focused_key` if a target is found.
    ///
    /// When `from_key` is not registered (e.g. the focused entry was
    /// unregistered during a virtualized scroll), falls back to the
    /// `First` direction (top-left-most entry in the active layer) instead
    /// of returning an error. Returns `Ok(None)` only when no entries
    /// exist at all.
    pub fn navigate(
        &self,
        from_key: &str,
        direction: crate::spatial_nav::Direction,
    ) -> Result<Option<FocusChanged>, String> {
        let mut inner = self.inner.write().unwrap();
        let source = match inner.entries.get(from_key) {
            Some(e) => e.clone(),
            None => return Self::fallback_to_first(&mut inner, from_key),
        };

        // Check override map before spatial search.
        let dir_str = direction.to_string();
        if let Some(override_val) = source.overrides.get(&dir_str) {
            return Self::apply_override(&mut inner, from_key, override_val);
        }

        Self::spatial_search(&mut inner, from_key, &source, direction)
    }

    /// Apply a navigation override: redirect to a moniker or block.
    ///
    /// `override_val` is `Some(moniker)` to redirect, `None` to block.
    /// Looks up the first spatial key registered for the target moniker
    /// in the active layer.
    fn apply_override(
        inner: &mut SpatialStateInner,
        from_key: &str,
        override_val: &Option<String>,
    ) -> Result<Option<FocusChanged>, String> {
        let target_moniker = match override_val {
            None => return Ok(None), // blocked
            Some(m) => m,
        };
        let active_layer_key = inner.layer_stack.active().map(|l| l.key.clone());
        let target_key = inner
            .entries
            .values()
            .find(|e| {
                e.moniker == *target_moniker
                    && e.key != from_key
                    && active_layer_key
                        .as_deref()
                        .map_or(true, |lk| e.layer_key == lk)
            })
            .map(|e| e.key.clone());
        match target_key {
            Some(key) => {
                let prev = inner.focused_key.take();
                if let Some(ref pk) = prev {
                    inner.save_focus_memory(pk);
                }
                inner.focused_key = Some(key.clone());
                Ok(Some(FocusChanged {
                    prev_key: prev,
                    next_key: Some(key),
                }))
            }
            None => Ok(None),
        }
    }

    /// Fallback when `from_key` is not registered: find the top-left-most
    /// entry in the active layer via `Direction::First` and set focus to it.
    ///
    /// Returns `Ok(None)` when the active layer has no entries.
    fn fallback_to_first(
        inner: &mut SpatialStateInner,
        _from_key: &str,
    ) -> Result<Option<FocusChanged>, String> {
        let active_layer_key = inner.layer_stack.active().map(|l| l.key.clone());
        let candidates: Vec<&SpatialEntry> = inner
            .entries
            .values()
            .filter(|e| {
                active_layer_key
                    .as_deref()
                    .map_or(true, |lk| e.layer_key == lk)
            })
            .collect();
        if candidates.is_empty() {
            return Ok(None);
        }
        // Reuse find_target with a dummy source — First ignores the source entry.
        let winner = crate::spatial_nav::find_target(
            candidates[0],
            &candidates,
            crate::spatial_nav::Direction::First,
        );
        match winner {
            Some(key) => {
                let prev = inner.focused_key.replace(key.clone());
                if let Some(ref pk) = prev {
                    inner.save_focus_memory(pk);
                }
                Ok(Some(FocusChanged {
                    prev_key: prev,
                    next_key: Some(key),
                }))
            }
            None => Ok(None),
        }
    }

    /// Run container-first spatial search and update focus if a target is found.
    fn spatial_search(
        inner: &mut SpatialStateInner,
        from_key: &str,
        source: &SpatialEntry,
        direction: crate::spatial_nav::Direction,
    ) -> Result<Option<FocusChanged>, String> {
        let active_layer_key = inner.layer_stack.active().map(|l| l.key.clone());
        let winner = {
            let candidates: Vec<&SpatialEntry> = inner
                .entries
                .values()
                .filter(|e| {
                    e.key != from_key
                        && active_layer_key
                            .as_deref()
                            .map_or(true, |lk| e.layer_key == lk)
                })
                .collect();
            crate::spatial_nav::container_first_search(source, &candidates, direction)
        };
        match winner {
            Some(key) => {
                let prev = inner.focused_key.take();
                if let Some(ref pk) = prev {
                    inner.save_focus_memory(pk);
                }
                inner.focused_key = Some(key.clone());
                Ok(Some(FocusChanged {
                    prev_key: prev,
                    next_key: Some(key),
                }))
            }
            None => Ok(None),
        }
    }
}

impl Default for SpatialState {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Helper to create a test rect at the given position.
    fn rect(x: f64, y: f64, w: f64, h: f64) -> Rect {
        Rect {
            x,
            y,
            width: w,
            height: h,
        }
    }

    /// Shorthand to register a spatial entry with no overrides.
    fn reg(
        state: &SpatialState,
        key: &str,
        moniker: &str,
        r: Rect,
        layer: &str,
        parent: Option<String>,
    ) {
        state.register(
            key.into(),
            moniker.into(),
            r,
            layer.into(),
            parent,
            HashMap::new(),
        );
    }

    // --- Focus tests (carried forward from card 0) ---

    #[test]
    fn spatial_focus_updates_focused_key_and_emits_event() {
        let state = SpatialState::new();
        reg(
            &state,
            "key-abc",
            "task:01",
            rect(0.0, 0.0, 100.0, 50.0),
            "layer-1",
            None,
        );

        let event = state.focus("key-abc");

        assert_eq!(state.focused_key(), Some("key-abc".to_string()));
        assert_eq!(
            event,
            Some(FocusChanged {
                prev_key: None,
                next_key: Some("key-abc".to_string()),
            })
        );
    }

    #[test]
    fn spatial_focus_emits_prev_and_next() {
        let state = SpatialState::new();
        reg(
            &state,
            "key-1",
            "task:01",
            rect(0.0, 0.0, 100.0, 50.0),
            "layer-1",
            None,
        );
        reg(
            &state,
            "key-2",
            "task:02",
            rect(200.0, 0.0, 100.0, 50.0),
            "layer-1",
            None,
        );
        state.focus("key-1");

        let event = state.focus("key-2");

        assert_eq!(
            event,
            Some(FocusChanged {
                prev_key: Some("key-1".to_string()),
                next_key: Some("key-2".to_string()),
            })
        );
    }

    #[test]
    fn spatial_focus_same_key_is_noop() {
        let state = SpatialState::new();
        reg(
            &state,
            "key-1",
            "task:01",
            rect(0.0, 0.0, 100.0, 50.0),
            "layer-1",
            None,
        );
        state.focus("key-1");

        let event = state.focus("key-1");
        assert!(event.is_none(), "focusing the same key should be a no-op");
    }

    #[test]
    fn spatial_unregister_focused_key_clears_focus() {
        let state = SpatialState::new();
        reg(
            &state,
            "key-1",
            "task:01",
            rect(0.0, 0.0, 100.0, 50.0),
            "layer-1",
            None,
        );
        state.focus("key-1");

        let event = state.unregister("key-1");

        assert_eq!(state.focused_key(), None);
        assert_eq!(
            event,
            Some(FocusChanged {
                prev_key: Some("key-1".to_string()),
                next_key: None,
            })
        );
    }

    #[test]
    fn spatial_unregister_non_focused_key_no_event() {
        let state = SpatialState::new();
        reg(
            &state,
            "key-1",
            "task:01",
            rect(0.0, 0.0, 100.0, 50.0),
            "layer-1",
            None,
        );
        reg(
            &state,
            "key-2",
            "task:02",
            rect(200.0, 0.0, 100.0, 50.0),
            "layer-1",
            None,
        );
        state.focus("key-1");

        let event = state.unregister("key-2");

        assert_eq!(
            state.focused_key(),
            Some("key-1".to_string()),
            "focused key should be unchanged"
        );
        assert!(event.is_none(), "no event when unfocused entry is removed");
    }

    #[test]
    fn register_overwrites_existing_entry() {
        let state = SpatialState::new();
        reg(
            &state,
            "key-1",
            "task:01",
            rect(0.0, 0.0, 100.0, 50.0),
            "layer-1",
            None,
        );
        reg(
            &state,
            "key-1",
            "task:02",
            rect(50.0, 50.0, 200.0, 100.0),
            "layer-2",
            None,
        );

        let entry = state.get("key-1").unwrap();
        assert_eq!(entry.moniker, "task:02");
        assert_eq!(entry.layer_key, "layer-2");
        assert_eq!(entry.rect.x, 50.0);
        assert_eq!(state.len(), 1);
    }

    #[test]
    fn unregister_nonexistent_key_is_noop() {
        let state = SpatialState::new();
        let event = state.unregister("nonexistent");
        assert!(event.is_none());
    }

    #[test]
    fn focus_unregistered_key_is_noop() {
        let state = SpatialState::new();
        let event = state.focus("unregistered");
        assert!(
            event.is_none(),
            "focusing an unregistered key should be a no-op"
        );
        assert_eq!(state.focused_key(), None);
    }

    #[test]
    fn clear_focus_emits_event() {
        let state = SpatialState::new();
        reg(
            &state,
            "key-1",
            "task:01",
            rect(0.0, 0.0, 100.0, 50.0),
            "layer-1",
            None,
        );
        state.focus("key-1");

        let event = state.clear_focus();
        assert_eq!(state.focused_key(), None);
        assert_eq!(
            event,
            Some(FocusChanged {
                prev_key: Some("key-1".to_string()),
                next_key: None,
            })
        );
    }

    #[test]
    fn clear_focus_when_unfocused_is_noop() {
        let state = SpatialState::new();
        let event = state.clear_focus();
        assert!(event.is_none());
    }

    #[test]
    fn empty_state() {
        let state = SpatialState::new();
        assert!(state.is_empty());
        assert_eq!(state.len(), 0);
        assert_eq!(state.focused_key(), None);
        assert!(state.get("anything").is_none());
    }

    // --- Registry tests (card 1) ---

    #[test]
    fn same_moniker_different_keys_both_stored() {
        let state = SpatialState::new();
        reg(
            &state,
            "key-A",
            "task:01",
            rect(0.0, 0.0, 100.0, 50.0),
            "layer-1",
            None,
        );
        reg(
            &state,
            "key-B",
            "task:01",
            rect(300.0, 0.0, 60.0, 20.0),
            "layer-1",
            None,
        );

        assert_eq!(state.len(), 2);
        assert_eq!(state.get("key-A").unwrap().moniker, "task:01");
        assert_eq!(state.get("key-B").unwrap().moniker, "task:01");
    }

    #[test]
    fn unregister_one_of_same_moniker_other_remains() {
        let state = SpatialState::new();
        reg(
            &state,
            "key-A",
            "task:01",
            rect(0.0, 0.0, 100.0, 50.0),
            "layer-1",
            None,
        );
        reg(
            &state,
            "key-B",
            "task:01",
            rect(300.0, 0.0, 60.0, 20.0),
            "layer-1",
            None,
        );

        state.unregister("key-A");

        assert_eq!(state.len(), 1);
        assert!(state.get("key-A").is_none());
        assert!(state.get("key-B").is_some());
    }

    #[test]
    fn update_rect_changes_rect_only() {
        let state = SpatialState::new();
        reg(
            &state,
            "key-1",
            "task:01",
            rect(0.0, 0.0, 100.0, 50.0),
            "layer-1",
            None,
        );

        state.update_rect("key-1", rect(10.0, 20.0, 200.0, 100.0));

        let entry = state.get("key-1").unwrap();
        assert_eq!(entry.rect, rect(10.0, 20.0, 200.0, 100.0));
        assert_eq!(entry.moniker, "task:01", "moniker unchanged");
        assert_eq!(entry.layer_key, "layer-1", "layer_key unchanged");
    }

    #[test]
    fn update_rect_nonexistent_key_is_noop() {
        let state = SpatialState::new();
        state.update_rect("nonexistent", rect(10.0, 20.0, 200.0, 100.0));
        assert!(state.is_empty());
    }

    // --- Layer stack tests (card 1) ---

    #[test]
    fn layer_stack_push_and_active() {
        let mut stack = LayerStack::default();
        stack.push("layer-A".into(), "window".into());

        assert_eq!(stack.active().unwrap().key, "layer-A");
        assert_eq!(stack.active().unwrap().name, "window");
        assert_eq!(stack.len(), 1);
    }

    #[test]
    fn layer_stack_topmost_is_active() {
        let mut stack = LayerStack::default();
        stack.push("layer-A".into(), "window".into());
        stack.push("layer-B".into(), "inspector".into());

        assert_eq!(stack.active().unwrap().key, "layer-B");
    }

    #[test]
    fn layer_stack_remove_middle_keeps_top() {
        let mut stack = LayerStack::default();
        stack.push("layer-A".into(), "window".into());
        stack.push("layer-B".into(), "inspector".into());
        stack.push("layer-C".into(), "dialog".into());

        let removed = stack.remove("layer-B");

        assert!(removed);
        assert_eq!(stack.len(), 2);
        assert_eq!(stack.active().unwrap().key, "layer-C", "topmost unchanged");
    }

    #[test]
    fn layer_stack_remove_top_reveals_previous() {
        let mut stack = LayerStack::default();
        stack.push("layer-A".into(), "window".into());
        stack.push("layer-B".into(), "inspector".into());

        stack.remove("layer-B");

        assert_eq!(stack.active().unwrap().key, "layer-A");
    }

    #[test]
    fn layer_stack_remove_all_leaves_empty() {
        let mut stack = LayerStack::default();
        stack.push("layer-A".into(), "window".into());
        stack.push("layer-B".into(), "inspector".into());

        stack.remove("layer-A");
        stack.remove("layer-B");

        assert!(stack.is_empty());
        assert!(stack.active().is_none());
    }

    #[test]
    fn layer_stack_remove_nonexistent_returns_false() {
        let mut stack = LayerStack::default();
        stack.push("layer-A".into(), "window".into());

        assert!(!stack.remove("nonexistent"));
        assert_eq!(stack.len(), 1);
    }

    #[test]
    fn spatial_state_layer_operations() {
        let state = SpatialState::new();
        state.push_layer("layer-A".into(), "window".into());
        state.push_layer("layer-B".into(), "inspector".into());

        assert_eq!(state.active_layer().unwrap().key, "layer-B");
        assert_eq!(state.layer_count(), 2);

        state.remove_layer("layer-A");
        assert_eq!(state.active_layer().unwrap().key, "layer-B");

        state.remove_layer("layer-B");
        assert!(state.active_layer().is_none());
        assert_eq!(state.layer_count(), 0);
    }

    // --- Navigate integration tests ---

    #[test]
    fn navigate_only_sees_active_layer() {
        let state = SpatialState::new();
        state.push_layer("window-layer".into(), "window".into());
        state.push_layer("inspector-layer".into(), "inspector".into());

        // Window layer: card
        reg(
            &state,
            "card",
            "task:01",
            rect(0.0, 0.0, 200.0, 60.0),
            "window-layer",
            None,
        );
        // Inspector layer (active): two fields
        reg(
            &state,
            "field-0",
            "field:title",
            rect(300.0, 0.0, 200.0, 35.0),
            "inspector-layer",
            None,
        );
        reg(
            &state,
            "field-1",
            "field:desc",
            rect(300.0, 40.0, 200.0, 35.0),
            "inspector-layer",
            None,
        );
        state.focus("field-0");

        // nav.right should NOT see the card (different layer)
        let result = state.navigate("field-0", crate::spatial_nav::Direction::Right);
        assert!(
            result.unwrap().is_none(),
            "card is in window layer, invisible to inspector"
        );

        // nav.down should find field-1
        let event = state
            .navigate("field-0", crate::spatial_nav::Direction::Down)
            .unwrap()
            .unwrap();
        assert_eq!(event.next_key, Some("field-1".to_string()));
    }

    #[test]
    fn navigate_with_unknown_key_falls_back() {
        let state = SpatialState::new();
        state.push_layer("layer".into(), "window".into());
        reg(
            &state,
            "key-1",
            "task:01",
            rect(0.0, 0.0, 100.0, 50.0),
            "layer",
            None,
        );

        // Unknown key falls back to First in active layer instead of Err.
        let result = state.navigate("nonexistent", crate::spatial_nav::Direction::Right);
        let event = result.unwrap().unwrap();
        assert_eq!(event.next_key, Some("key-1".to_string()));
    }

    #[test]
    fn navigate_with_no_candidates_is_noop() {
        let state = SpatialState::new();
        state.push_layer("layer".into(), "window".into());
        reg(
            &state,
            "only",
            "task:01",
            rect(0.0, 0.0, 100.0, 50.0),
            "layer",
            None,
        );
        state.focus("only");

        let result = state.navigate("only", crate::spatial_nav::Direction::Right);
        assert!(result.unwrap().is_none(), "single entry has no candidates");
        assert_eq!(
            state.focused_key(),
            Some("only".to_string()),
            "focus unchanged"
        );
    }

    #[test]
    fn layer_remove_restores_last_focused() {
        let state = SpatialState::new();
        state.push_layer("window-layer".into(), "window".into());

        // Register and focus card-A in window layer
        reg(
            &state,
            "card-A",
            "task:01",
            rect(0.0, 0.0, 200.0, 60.0),
            "window-layer",
            None,
        );
        state.focus("card-A");

        // Push inspector layer, register fields, focus field-1 then field-3
        state.push_layer("inspector-layer".into(), "inspector".into());
        reg(
            &state,
            "field-1",
            "field:1",
            rect(300.0, 0.0, 200.0, 35.0),
            "inspector-layer",
            None,
        );
        reg(
            &state,
            "field-3",
            "field:3",
            rect(300.0, 80.0, 200.0, 35.0),
            "inspector-layer",
            None,
        );
        state.focus("field-1");
        state.focus("field-3");

        // Remove inspector layer → should restore card-A
        let event = state.remove_layer("inspector-layer");
        assert!(
            event.is_some(),
            "should emit focus-changed restoring card-A"
        );
        let fc = event.unwrap();
        assert_eq!(fc.prev_key, Some("field-3".to_string()));
        assert_eq!(fc.next_key, Some("card-A".to_string()));
        assert_eq!(state.focused_key(), Some("card-A".to_string()));
    }

    // --- Override tests ---

    #[test]
    fn navigate_with_override_returns_override_target() {
        let state = SpatialState::new();
        state.push_layer("layer".into(), "window".into());

        let mut overrides = HashMap::new();
        overrides.insert("Right".to_string(), Some("task:02".to_string()));
        state.register(
            "key-1".into(),
            "task:01".into(),
            rect(0.0, 0.0, 100.0, 50.0),
            "layer".into(),
            None,
            overrides,
        );
        reg(
            &state,
            "key-2",
            "task:02",
            rect(200.0, 0.0, 100.0, 50.0),
            "layer",
            None,
        );
        state.focus("key-1");

        let event = state
            .navigate("key-1", crate::spatial_nav::Direction::Right)
            .unwrap()
            .unwrap();
        assert_eq!(event.next_key, Some("key-2".to_string()));
    }

    #[test]
    fn navigate_with_null_override_returns_none() {
        let state = SpatialState::new();
        state.push_layer("layer".into(), "window".into());

        let mut overrides = HashMap::new();
        overrides.insert("Left".to_string(), None);
        state.register(
            "key-1".into(),
            "task:01".into(),
            rect(100.0, 0.0, 100.0, 50.0),
            "layer".into(),
            None,
            overrides,
        );
        reg(
            &state,
            "key-2",
            "task:02",
            rect(0.0, 0.0, 100.0, 50.0),
            "layer",
            None,
        );
        state.focus("key-1");

        // Left is blocked (null override) even though key-2 is to the left
        let result = state.navigate("key-1", crate::spatial_nav::Direction::Left);
        assert!(
            result.unwrap().is_none(),
            "null override should block navigation"
        );
        assert_eq!(
            state.focused_key(),
            Some("key-1".to_string()),
            "focus unchanged"
        );
    }

    #[test]
    fn navigate_without_override_falls_through_to_spatial() {
        let state = SpatialState::new();
        state.push_layer("layer".into(), "window".into());

        // Override only exists for Right, not Down
        let mut overrides = HashMap::new();
        overrides.insert("Right".to_string(), Some("task:03".to_string()));
        state.register(
            "key-1".into(),
            "task:01".into(),
            rect(0.0, 0.0, 100.0, 50.0),
            "layer".into(),
            None,
            overrides,
        );
        reg(
            &state,
            "key-2",
            "task:02",
            rect(0.0, 60.0, 100.0, 50.0),
            "layer",
            None,
        );
        state.focus("key-1");

        // Down has no override — falls through to spatial nav, finds key-2 below
        let event = state
            .navigate("key-1", crate::spatial_nav::Direction::Down)
            .unwrap()
            .unwrap();
        assert_eq!(event.next_key, Some("key-2".to_string()));
    }

    // --- Navigate fallback tests ---

    #[test]
    fn navigate_missing_key_falls_back_to_first() {
        let state = SpatialState::new();
        state.push_layer("layer".into(), "window".into());
        reg(
            &state,
            "key-A",
            "task:01",
            rect(200.0, 100.0, 100.0, 50.0),
            "layer",
            None,
        );
        reg(
            &state,
            "key-B",
            "task:02",
            rect(0.0, 0.0, 100.0, 50.0),
            "layer",
            None,
        );
        reg(
            &state,
            "key-C",
            "task:03",
            rect(100.0, 50.0, 100.0, 50.0),
            "layer",
            None,
        );

        // "gone" is not registered — should fall back to top-left (key-B at 0,0).
        let result = state.navigate("gone", crate::spatial_nav::Direction::Down);
        let event = result.unwrap().unwrap();
        assert_eq!(event.next_key, Some("key-B".to_string()));
        assert_eq!(state.focused_key(), Some("key-B".to_string()));
    }

    #[test]
    fn navigate_missing_key_empty_layer_is_noop() {
        let state = SpatialState::new();
        state.push_layer("layer".into(), "window".into());
        // No entries at all.
        let result = state.navigate("gone", crate::spatial_nav::Direction::Right);
        assert!(result.unwrap().is_none());
    }

    // --- Batch registration tests ---

    #[test]
    fn register_batch_adds_multiple_entries() {
        let state = SpatialState::new();
        state.register_batch(vec![
            BatchEntry {
                key: "k1".into(),
                moniker: "task:01".into(),
                rect: rect(0.0, 0.0, 100.0, 50.0),
                layer_key: "layer".into(),
                parent_scope: None,
                overrides: HashMap::new(),
            },
            BatchEntry {
                key: "k2".into(),
                moniker: "task:02".into(),
                rect: rect(0.0, 60.0, 100.0, 50.0),
                layer_key: "layer".into(),
                parent_scope: None,
                overrides: HashMap::new(),
            },
            BatchEntry {
                key: "k3".into(),
                moniker: "task:03".into(),
                rect: rect(0.0, 120.0, 100.0, 50.0),
                layer_key: "layer".into(),
                parent_scope: None,
                overrides: HashMap::new(),
            },
        ]);

        assert_eq!(state.len(), 3);
        assert_eq!(state.get("k1").unwrap().moniker, "task:01");
        assert_eq!(state.get("k2").unwrap().moniker, "task:02");
        assert_eq!(state.get("k3").unwrap().moniker, "task:03");
    }

    #[test]
    fn unregister_batch_removes_entries_and_clears_focus() {
        let state = SpatialState::new();
        reg(
            &state,
            "k1",
            "task:01",
            rect(0.0, 0.0, 100.0, 50.0),
            "layer",
            None,
        );
        reg(
            &state,
            "k2",
            "task:02",
            rect(0.0, 60.0, 100.0, 50.0),
            "layer",
            None,
        );
        reg(
            &state,
            "k3",
            "task:03",
            rect(0.0, 120.0, 100.0, 50.0),
            "layer",
            None,
        );
        state.focus("k2");

        let event = state.unregister_batch(&["k1".into(), "k2".into()]);

        assert_eq!(state.len(), 1);
        assert!(state.get("k1").is_none());
        assert!(state.get("k2").is_none());
        assert!(state.get("k3").is_some());
        assert_eq!(
            state.focused_key(),
            None,
            "focus cleared because k2 was removed"
        );
        assert!(event.is_some(), "should emit FocusChanged");
        assert_eq!(event.unwrap().prev_key, Some("k2".to_string()));
    }

    // --- Rect tests ---

    #[test]
    fn rect_right_and_bottom() {
        let r = rect(10.0, 20.0, 100.0, 50.0);
        assert_eq!(r.right(), 110.0);
        assert_eq!(r.bottom(), 70.0);
    }

    #[test]
    fn rect_default_is_zero_origin_zero_size() {
        let r = Rect::default();
        assert_eq!(r, rect(0.0, 0.0, 0.0, 0.0));
    }

    // --- Coverage gap tests (card 01KPG70ZNP0X7WE06SXJVV1N9C) ---

    /// `navigate()` with `overrides` — three cases asserted independently:
    /// - `Some(Some(target))` redirects to the target moniker
    /// - `Some(None)` blocks navigation (returns no event)
    /// - Missing direction key falls through to the spatial beam test
    #[test]
    fn navigate_override_redirect_block_and_fallthrough() {
        let state = SpatialState::new();
        state.push_layer("layer".into(), "window".into());

        // key-1 has a `Right` redirect to task:03, a `Left` block,
        // and no entry for `Down` (falls through to spatial).
        let mut overrides = HashMap::new();
        overrides.insert("Right".to_string(), Some("task:03".to_string()));
        overrides.insert("Left".to_string(), None);
        state.register(
            "key-1".into(),
            "task:01".into(),
            rect(100.0, 100.0, 100.0, 50.0),
            "layer".into(),
            None,
            overrides,
        );
        // key-2 sits directly to the left of key-1 — would be the natural
        // spatial `Left` target if the override didn't block.
        reg(
            &state,
            "key-2",
            "task:02",
            rect(0.0, 100.0, 100.0, 50.0),
            "layer",
            None,
        );
        // key-3 is the redirect target, placed far away so only the
        // override (not spatial beam) could select it for `Right`.
        reg(
            &state,
            "key-3",
            "task:03",
            rect(900.0, 900.0, 100.0, 50.0),
            "layer",
            None,
        );
        // key-4 sits directly below key-1 — natural spatial `Down` target.
        reg(
            &state,
            "key-4",
            "task:04",
            rect(100.0, 200.0, 100.0, 50.0),
            "layer",
            None,
        );
        state.focus("key-1");

        // Case 1: Some(Some("task:03")) → redirect to key-3 (the moniker holder).
        let event = state
            .navigate("key-1", crate::spatial_nav::Direction::Right)
            .unwrap()
            .unwrap();
        assert_eq!(
            event.next_key,
            Some("key-3".to_string()),
            "Right override should redirect to the entry holding task:03"
        );

        // Restore focus for next case (override moved focus to key-3).
        state.focus("key-1");

        // Case 2: Some(None) → block — no event, focus unchanged.
        let result = state
            .navigate("key-1", crate::spatial_nav::Direction::Left)
            .unwrap();
        assert!(
            result.is_none(),
            "null override should block navigation and emit no event"
        );
        assert_eq!(
            state.focused_key(),
            Some("key-1".to_string()),
            "focus must not change when blocked"
        );

        // Case 3: missing key → fall through to spatial beam test, finds key-4 below.
        let event = state
            .navigate("key-1", crate::spatial_nav::Direction::Down)
            .unwrap()
            .unwrap();
        assert_eq!(
            event.next_key,
            Some("key-4".to_string()),
            "Down has no override, spatial fallback should find key-4"
        );
    }

    /// Entries on inactive layers must never be candidates for `navigate()`.
    /// Register one entry on layer A, push layer B on top, then navigate
    /// from an entry on layer B — the layer-A entry must be invisible.
    #[test]
    fn navigate_layer_filter_excludes_inactive_layer_entries() {
        let state = SpatialState::new();
        state.push_layer("layer-A".into(), "window".into());
        state.push_layer("layer-B".into(), "inspector".into());

        // layer-A entry sitting directly to the right of the layer-B source —
        // would be a natural spatial winner if the layer filter didn't exclude it.
        reg(
            &state,
            "a-right",
            "task:01",
            rect(200.0, 0.0, 100.0, 50.0),
            "layer-A",
            None,
        );
        // layer-B source (active layer).
        reg(
            &state,
            "b-source",
            "task:02",
            rect(0.0, 0.0, 100.0, 50.0),
            "layer-B",
            None,
        );
        state.focus("b-source");

        // No candidates on the active layer in that direction — must return
        // None, never select the layer-A entry.
        let result = state
            .navigate("b-source", crate::spatial_nav::Direction::Right)
            .unwrap();
        assert!(
            result.is_none(),
            "layer-A entry must be filtered out; no candidate on active layer"
        );
        assert_eq!(
            state.focused_key(),
            Some("b-source".to_string()),
            "focus must not move to a non-active-layer entry"
        );
    }

    /// Cross-layer `focus()` writes `last_focused` to the outgoing layer,
    /// not the incoming one. With both layers stacked and an entry focused
    /// on layer A, calling `focus()` on a layer-B entry (not via a layer
    /// push) must record layer A's `last_focused`.
    #[test]
    fn focus_across_layers_writes_last_focused_to_outgoing_layer() {
        let state = SpatialState::new();
        state.push_layer("layer-A".into(), "window".into());
        state.push_layer("layer-B".into(), "inspector".into());

        reg(
            &state,
            "a-entry",
            "task:01",
            rect(0.0, 0.0, 100.0, 50.0),
            "layer-A",
            None,
        );
        reg(
            &state,
            "b-entry",
            "field:01",
            rect(300.0, 0.0, 100.0, 50.0),
            "layer-B",
            None,
        );

        // Focus lands on layer-A first.
        state.focus("a-entry");
        // Then switch focus across layers (not via push/remove).
        let event = state.focus("b-entry");
        assert_eq!(
            event,
            Some(FocusChanged {
                prev_key: Some("a-entry".to_string()),
                next_key: Some("b-entry".to_string()),
            })
        );

        // Remove layer-B — layer-A is now active; its last_focused should
        // be "a-entry", restored by remove_layer's restore path.
        let restore = state.remove_layer("layer-B");
        assert_eq!(
            restore,
            Some(FocusChanged {
                prev_key: Some("b-entry".to_string()),
                next_key: Some("a-entry".to_string()),
            }),
            "layer-A's last_focused must be a-entry (the outgoing key when \
             focus moved to layer-B), not b-entry"
        );
        assert_eq!(state.focused_key(), Some("a-entry".to_string()));
    }

    /// `unregister_batch` that includes the focused key emits `focus-changed`
    /// exactly once with `next_key: None`, regardless of how many keys were
    /// removed in the batch.
    #[test]
    fn unregister_batch_with_focused_key_emits_focus_changed_once() {
        let state = SpatialState::new();
        reg(
            &state,
            "k1",
            "task:01",
            rect(0.0, 0.0, 100.0, 50.0),
            "layer",
            None,
        );
        reg(
            &state,
            "k2",
            "task:02",
            rect(0.0, 60.0, 100.0, 50.0),
            "layer",
            None,
        );
        reg(
            &state,
            "k3",
            "task:03",
            rect(0.0, 120.0, 100.0, 50.0),
            "layer",
            None,
        );
        state.focus("k2");

        // Batch removes the focused key plus an unfocused key.
        let event = state.unregister_batch(&["k1".into(), "k2".into()]);

        // Exactly one event, with the focused key as prev and null as next.
        assert_eq!(
            event,
            Some(FocusChanged {
                prev_key: Some("k2".to_string()),
                next_key: None,
            }),
            "single focus-changed with next_key: null when focused key is in batch"
        );
        assert_eq!(state.focused_key(), None);
    }
}
