/**
 * TypeScript branded types mirroring the Rust newtypes from
 * `swissarmyhammer-kanban/src/focus/types.rs`.
 *
 * Each branded type is a string with a phantom `__brand` property, which
 * means a plain `string` cannot be passed where a `WindowLabel` is expected
 * (and vice versa) — the structural compatibility that normally makes
 * TypeScript loose around primitives is broken on purpose. The brand
 * symbol field is never actually present at runtime; the wire shape is
 * still a bare string thanks to `#[serde(transparent)]` on the Rust side.
 *
 * Use the `as*` helpers to convert from a plain string when you receive
 * a value from outside the typed surface (e.g. a DOM dataset attribute or
 * a serialized URL parameter). The helpers do not validate — they encode
 * the intent that the caller has asserted the value is well-formed.
 *
 * The `Direction` and `FocusChangedPayload` types encode the wire shapes
 * that cross the Tauri IPC boundary; updating either one in Rust requires
 * matching the change here.
 */

// ---------------------------------------------------------------------------
// Branded primitive types
// ---------------------------------------------------------------------------

/**
 * Tauri window label — which window a scope/layer lives in.
 *
 * Mirrors `swissarmyhammer_kanban::focus::types::WindowLabel`. The frontend
 * derives this from `appWindow.label` (the Tauri-supplied window handle);
 * never construct one from a user-supplied string.
 */
export type WindowLabel = string & { readonly __brand: "WindowLabel" };

/**
 * Unique key per `<FocusScope>` / `<FocusZone>` instance.
 *
 * Mirrors `swissarmyhammer_kanban::focus::types::SpatialKey`. Each component
 * mints exactly one of these on mount via `crypto.randomUUID()` and
 * unregisters it on unmount. The registry only requires uniqueness; the
 * key shape (UUIDv4 today) is an implementation detail of the React
 * primitives, not a wire contract.
 */
export type SpatialKey = string & { readonly __brand: "SpatialKey" };

/**
 * Unique key per `<FocusLayer>` instance — modal boundaries (window,
 * inspector, dialog, palette).
 *
 * Mirrors `swissarmyhammer_kanban::focus::types::LayerKey`. Minted via
 * `crypto.randomUUID()`; uniqueness is the only requirement.
 */
export type LayerKey = string & { readonly __brand: "LayerKey" };

/**
 * Entity focus identity such as `"task:01ABC"` or `"ui:toolbar.new"`.
 *
 * Mirrors `swissarmyhammer_kanban::focus::types::Moniker`. Read off
 * `<FocusScope>` props or generated by the entity rendering layer; never
 * derived from user input directly.
 */
export type Moniker = string & { readonly __brand: "Moniker" };

/**
 * Layer role tag — `"window"`, `"inspector"`, `"dialog"`, `"palette"`.
 *
 * Mirrors `swissarmyhammer_kanban::focus::types::LayerName`.
 */
export type LayerName = string & { readonly __brand: "LayerName" };

/**
 * Logical pixels for spatial-nav rect math.
 *
 * Mirrors `swissarmyhammer_kanban::focus::types::Pixels`. The `number`
 * brand keeps `Pixels` from accidentally trading places with other
 * numeric values (zoom factors, ordinal indices) in spatial-nav code.
 */
export type Pixels = number & { readonly __brand: "Pixels" };

// ---------------------------------------------------------------------------
// Brand helpers
// ---------------------------------------------------------------------------

/**
 * Tag a plain string as a `WindowLabel`.
 *
 * Used at the IPC boundary — `appWindow.label` returns a plain `string`,
 * and this helper records that the caller has asserted the value is in
 * fact a Tauri window label.
 */
export const asWindowLabel = (s: string): WindowLabel => s as WindowLabel;

/** Tag a plain string as a `SpatialKey`. */
export const asSpatialKey = (s: string): SpatialKey => s as SpatialKey;

/** Tag a plain string as a `LayerKey`. */
export const asLayerKey = (s: string): LayerKey => s as LayerKey;

/** Tag a plain string as a `Moniker`. */
export const asMoniker = (s: string): Moniker => s as Moniker;

/** Tag a plain string as a `LayerName`. */
export const asLayerName = (s: string): LayerName => s as LayerName;

/** Tag a plain number as `Pixels`. */
export const asPixels = (n: number): Pixels => n as Pixels;

// ---------------------------------------------------------------------------
// Direction enum — matches the Rust `Direction` serialization
// ---------------------------------------------------------------------------

/**
 * Navigation direction.
 *
 * Mirrors the lower-cased serialization of
 * `swissarmyhammer_focus::types::Direction`. The Rust enum derives
 * `#[serde(rename_all = "lowercase")]`, so the wire shape is the
 * string literal — that is what this union encodes.
 *
 * The four cardinal arrows (`up`/`down`/`left`/`right`) drive the
 * Android-style beam-search algorithm. The four edge commands jump to
 * the boundaries of the active scope:
 *
 * - `first` / `last` — topmost-leftmost / bottommost-rightmost
 *   candidate at the focused level (in-zone for leaves, sibling-zone
 *   for zones).
 * - `rowstart` / `rowend` — leftmost / rightmost candidate whose
 *   vertical extent overlaps the focused rect (start / end of the
 *   focused row).
 *
 * Drill-in / drill-out are separate commands, not directions.
 */
export type Direction =
  | "up"
  | "down"
  | "left"
  | "right"
  | "first"
  | "last"
  | "rowstart"
  | "rowend";

// ---------------------------------------------------------------------------
// Wire payloads
// ---------------------------------------------------------------------------

/**
 * Wire payload for the `focus-changed` Tauri event.
 *
 * Mirrors `swissarmyhammer_kanban::focus::state::FocusChangedEvent`. Field
 * names use snake_case to match Rust's serde defaults; if Rust ever moves
 * to camelCase via `#[serde(rename_all = "camelCase")]` this type must
 * change in lockstep.
 */
export interface FocusChangedPayload {
  /** Window in which focus changed. */
  readonly window_label: WindowLabel;
  /** Previously focused spatial key, if any. */
  readonly prev_key: SpatialKey | null;
  /** Newly focused spatial key, if any. */
  readonly next_key: SpatialKey | null;
  /** Moniker of the newly focused entity, if `next_key` is non-null. */
  readonly next_moniker: Moniker | null;
}

/**
 * Axis-aligned rectangle in viewport pixel coordinates.
 *
 * Mirrors `swissarmyhammer_kanban::focus::types::Rect`. `x` / `y` are the
 * top-left corner; `width` / `height` are non-negative extents. `Pixels`
 * is a branded `number` so accidentally passing a zoom factor (or an
 * ordinal) where a pixel value is expected is a compile error.
 */
export interface Rect {
  readonly x: Pixels;
  readonly y: Pixels;
  readonly width: Pixels;
  readonly height: Pixels;
}

/**
 * Per-direction navigation overrides for a `<FocusScope>` or `<FocusZone>`.
 *
 * Mirrors `HashMap<Direction, Option<Moniker>>` on the Rust side. Missing
 * keys mean "fall through to beam search"; an explicit `null` value is a
 * "wall" that blocks navigation in that direction; a string value is a
 * redirect to the named moniker.
 */
export type FocusOverrides = Partial<Record<Direction, Moniker | null>>;
