//! Shared build utilities for SwissArmyHammer crates.
//!
//! This crate provides common functionality for build.rs scripts that need to
//! embed builtin files (prompts, rules, workflows, validators, etc.) into the
//! binary at compile time.
//!
//! # Example
//!
//! ```ignore
//! // In build.rs:
//! use swissarmyhammer_build::BuiltinGenerator;
//!
//! fn main() {
//!     BuiltinGenerator::new("validators")
//!         .source_dir("../builtin/validators")
//!         .extensions(&["md"])
//!         .function_name("get_builtin_validators")
//!         .generate();
//! }
//! ```

use std::env;
use std::fmt::Write;
use std::fs;
use std::path::{Path, PathBuf};

/// Configuration for generating builtin embedding code.
pub struct BuiltinGenerator {
    /// Name of the resource type (for comments)
    resource_type: String,
    /// Source directory relative to manifest dir
    source_dir: String,
    /// Output file name (without .rs)
    output_name: String,
    /// Function name to generate
    function_name: String,
    /// File extensions to include
    extensions: Vec<String>,
    /// Directories to skip
    skip_dirs: Vec<String>,
    /// When true, preserve file extensions in generated names.
    /// When false (default), extensions are stripped so names serve as identifiers.
    preserve_extensions: bool,
}

impl BuiltinGenerator {
    /// Create a new generator for a resource type.
    ///
    /// # Arguments
    /// * `resource_type` - The type of resource (e.g., "prompts", "validators")
    pub fn new(resource_type: impl Into<String>) -> Self {
        let resource_type = resource_type.into();
        Self {
            output_name: format!("builtin_{}", resource_type),
            function_name: format!("get_builtin_{}", resource_type),
            source_dir: format!("../builtin/{}", resource_type),
            resource_type,
            extensions: vec!["md".to_string()],
            skip_dirs: vec![],
            preserve_extensions: false,
        }
    }

    /// Set the source directory relative to the crate's manifest directory.
    pub fn source_dir(mut self, dir: impl Into<String>) -> Self {
        self.source_dir = dir.into();
        self
    }

    /// Set the output file name (without .rs extension).
    pub fn output_name(mut self, name: impl Into<String>) -> Self {
        self.output_name = name.into();
        self
    }

    /// Set the function name to generate.
    pub fn function_name(mut self, name: impl Into<String>) -> Self {
        self.function_name = name.into();
        self
    }

    /// Set the file extensions to include (without leading dot).
    pub fn extensions(mut self, exts: &[&str]) -> Self {
        self.extensions = exts.iter().map(|s| s.to_string()).collect();
        self
    }

    /// Set directories to skip during collection.
    pub fn skip_dirs(mut self, dirs: &[&str]) -> Self {
        self.skip_dirs = dirs.iter().map(|s| s.to_string()).collect();
        self
    }

    /// Preserve file extensions in generated resource names.
    ///
    /// By default, extensions are stripped so names act as identifiers
    /// (e.g., `plan/SKILL` from `plan/SKILL.md`). When enabled, the full
    /// filename is kept (e.g., `plan/SKILL.md`), which is needed for
    /// multi-file resources where filenames are written to disk.
    pub fn preserve_extensions(mut self) -> Self {
        self.preserve_extensions = true;
        self
    }

    /// Generate the builtin embedding code.
    ///
    /// This should be called from build.rs. It will:
    /// 1. Set up cargo rerun-if-changed directives
    /// 2. Generate Rust code that embeds all matching files
    /// 3. Write the code to OUT_DIR
    pub fn generate(&self) {
        let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
        let out_dir = env::var("OUT_DIR").unwrap();

        let builtin_dir = Path::new(&manifest_dir).join(&self.source_dir);

        // Tell Cargo to rerun if the source directory changes
        println!("cargo:rerun-if-changed={}", builtin_dir.display());

        let dest_path = Path::new(&out_dir).join(format!("{}.rs", self.output_name));

        let code = self.generate_code(&builtin_dir);
        fs::write(&dest_path, code).unwrap();
    }

    /// Generate the Rust code for embedding builtins.
    fn generate_code(&self, builtin_dir: &Path) -> String {
        let mut code = String::new();

        writeln!(
            code,
            "// Auto-generated builtin {} - do not edit manually",
            self.resource_type
        )
        .unwrap();
        writeln!(
            code,
            "// Generated by build.rs from {} directory\n",
            self.source_dir
        )
        .unwrap();

        writeln!(
            code,
            "/// Get all built-in {} as a vector of (name, content) tuples",
            self.resource_type
        )
        .unwrap();
        writeln!(
            code,
            "pub fn {}() -> Vec<(&'static str, &'static str)> {{",
            self.function_name
        )
        .unwrap();
        code.push_str("    vec![\n");

        if builtin_dir.exists() {
            self.collect_files(builtin_dir, "", &mut code);
        }

        code.push_str("    ]\n");
        code.push_str("}\n");

        code
    }

    /// Recursively collect files from a directory.
    fn collect_files(&self, dir: &Path, prefix: &str, code: &mut String) {
        let Ok(entries) = fs::read_dir(dir) else {
            return;
        };

        let mut entries: Vec<_> = entries.collect();
        entries.sort_by_key(|entry| entry.as_ref().unwrap().path());

        for entry in entries.into_iter().flatten() {
            let path = entry.path();
            let name = path.file_name().unwrap().to_string_lossy();

            if path.is_dir() {
                // Skip configured directories
                if self.skip_dirs.contains(&name.to_string()) {
                    continue;
                }

                // Recursively collect from subdirectories
                let new_prefix = if prefix.is_empty() {
                    name.to_string()
                } else {
                    format!("{prefix}/{name}")
                };
                self.collect_files(&path, &new_prefix, code);
            } else if self.matches_extension(&path) {
                // Tell Cargo to rerun if this file changes
                println!("cargo:rerun-if-changed={}", path.display());

                // Generate the resource name
                let resource_name = self.extract_name(&path, prefix);

                // Read the file content at build time and embed it as a string literal
                if let Ok(content) = fs::read_to_string(&path) {
                    let hashes = raw_string_hashes(&content);
                    writeln!(
                        code,
                        "        (\"{resource_name}\", r{hashes}\"{content}\"{hashes}),"
                    )
                    .unwrap();
                }
            }
        }
    }

    /// Check if a file matches any of the configured extensions.
    fn matches_extension(&self, path: &Path) -> bool {
        let Some(ext) = path.extension() else {
            return false;
        };
        let ext = ext.to_string_lossy();
        self.extensions.iter().any(|e| e == ext.as_ref())
    }

    /// Extract the resource name from a file path.
    ///
    /// When `preserve_extensions` is false (default), strips known extensions
    /// so names serve as identifiers. When true, keeps the full filename.
    fn extract_name(&self, path: &Path, prefix: &str) -> String {
        let name = path.file_name().unwrap().to_string_lossy();

        let base_name = if self.preserve_extensions {
            name.to_string()
        } else {
            self.extensions
                .iter()
                .find_map(|ext| name.strip_suffix(&format!(".{}", ext)))
                .unwrap_or(&name)
                .to_string()
        };

        if prefix.is_empty() {
            base_name
        } else {
            format!("{}/{}", prefix, base_name)
        }
    }
}

/// Determine the number of `#` characters needed for a raw string literal.
///
/// Scans the content for `"` followed by `#` sequences, and returns a string
/// of `#` characters one longer than the longest such sequence found.
fn raw_string_hashes(content: &str) -> String {
    let mut max_hashes = 0usize;
    for (i, _) in content.match_indices('"') {
        let after = &content[i + 1..];
        let count = after.chars().take_while(|&c| c == '#').count();
        max_hashes = max_hashes.max(count + 1);
    }
    "#".repeat(max_hashes)
}

/// Helper to get the manifest directory.
pub fn manifest_dir() -> PathBuf {
    PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap())
}

/// Helper to get the OUT_DIR.
pub fn out_dir() -> PathBuf {
    PathBuf::from(env::var("OUT_DIR").unwrap())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn test_generator_defaults() {
        let gen = BuiltinGenerator::new("validators");
        assert_eq!(gen.resource_type, "validators");
        assert_eq!(gen.source_dir, "../builtin/validators");
        assert_eq!(gen.output_name, "builtin_validators");
        assert_eq!(gen.function_name, "get_builtin_validators");
        assert_eq!(gen.extensions, vec!["md"]);
        assert!(!gen.preserve_extensions);
        assert!(gen.skip_dirs.is_empty());
    }

    #[test]
    fn test_generator_customization() {
        let gen = BuiltinGenerator::new("prompts")
            .source_dir("custom/prompts")
            .extensions(&["md", "liquid"])
            .skip_dirs(&["workflows"]);

        assert_eq!(gen.source_dir, "custom/prompts");
        assert_eq!(gen.extensions, vec!["md", "liquid"]);
        assert_eq!(gen.skip_dirs, vec!["workflows"]);
    }

    #[test]
    fn test_output_name_builder() {
        let gen = BuiltinGenerator::new("prompts").output_name("my_prompts");
        assert_eq!(gen.output_name, "my_prompts");
    }

    #[test]
    fn test_function_name_builder() {
        let gen = BuiltinGenerator::new("prompts").function_name("load_prompts");
        assert_eq!(gen.function_name, "load_prompts");
    }

    #[test]
    fn test_preserve_extensions_builder() {
        let gen = BuiltinGenerator::new("skills").preserve_extensions();
        assert!(gen.preserve_extensions);
    }

    // -- raw_string_hashes tests --

    #[test]
    fn test_raw_string_hashes_no_quotes() {
        assert_eq!(raw_string_hashes("hello world"), "");
    }

    #[test]
    fn test_raw_string_hashes_simple_quote() {
        // A bare quote needs one hash to disambiguate
        assert_eq!(raw_string_hashes("say \"hello\""), "#");
    }

    #[test]
    fn test_raw_string_hashes_quote_followed_by_hashes() {
        // A quote followed by two hashes needs 3 hashes to disambiguate
        let input = "foo\"##bar";
        assert_eq!(raw_string_hashes(input), "###");
    }

    #[test]
    fn test_raw_string_hashes_empty_string() {
        assert_eq!(raw_string_hashes(""), "");
    }

    #[test]
    fn test_raw_string_hashes_multiple_quote_sequences() {
        // A quote-hash needs 2 hashes; a bare quote needs 1 — max wins
        let input = "a\"#b and c\"d";
        assert_eq!(raw_string_hashes(input), "##");
    }

    // -- matches_extension tests --

    #[test]
    fn test_matches_extension_positive() {
        let gen = BuiltinGenerator::new("prompts").extensions(&["md", "yaml"]);
        assert!(gen.matches_extension(Path::new("foo.md")));
        assert!(gen.matches_extension(Path::new("bar.yaml")));
    }

    #[test]
    fn test_matches_extension_negative() {
        let gen = BuiltinGenerator::new("prompts").extensions(&["md"]);
        assert!(!gen.matches_extension(Path::new("foo.txt")));
    }

    #[test]
    fn test_matches_extension_no_extension() {
        let gen = BuiltinGenerator::new("prompts");
        assert!(!gen.matches_extension(Path::new("Makefile")));
    }

    // -- extract_name tests --

    #[test]
    fn test_extract_name_strips_extension() {
        let gen = BuiltinGenerator::new("prompts").extensions(&["md"]);
        let name = gen.extract_name(Path::new("SKILL.md"), "");
        assert_eq!(name, "SKILL");
    }

    #[test]
    fn test_extract_name_with_prefix() {
        let gen = BuiltinGenerator::new("prompts").extensions(&["md"]);
        let name = gen.extract_name(Path::new("SKILL.md"), "plan");
        assert_eq!(name, "plan/SKILL");
    }

    #[test]
    fn test_extract_name_preserve_extensions() {
        let gen = BuiltinGenerator::new("skills")
            .extensions(&["md"])
            .preserve_extensions();
        let name = gen.extract_name(Path::new("SKILL.md"), "");
        assert_eq!(name, "SKILL.md");
    }

    #[test]
    fn test_extract_name_preserve_extensions_with_prefix() {
        let gen = BuiltinGenerator::new("skills")
            .extensions(&["md"])
            .preserve_extensions();
        let name = gen.extract_name(Path::new("SKILL.md"), "plan");
        assert_eq!(name, "plan/SKILL.md");
    }

    #[test]
    fn test_extract_name_unknown_extension_not_stripped() {
        let gen = BuiltinGenerator::new("prompts").extensions(&["md"]);
        // .txt is not in extensions, so strip_suffix won't match — falls back to full name
        let name = gen.extract_name(Path::new("README.txt"), "");
        assert_eq!(name, "README.txt");
    }

    // -- generate_code tests --

    #[test]
    fn test_generate_code_nonexistent_dir() {
        let gen = BuiltinGenerator::new("widgets");
        let code = gen.generate_code(Path::new("/nonexistent/dir"));
        assert!(code.contains("pub fn get_builtin_widgets()"));
        assert!(code.contains("vec!["));
        // No files collected — empty vec
        assert!(!code.contains("(\""));
    }

    #[test]
    fn test_generate_code_with_files() {
        let tmp = tempdir();
        fs::write(tmp.join("alpha.md"), "# Alpha content").unwrap();
        fs::write(tmp.join("beta.md"), "# Beta content").unwrap();

        let gen = BuiltinGenerator::new("docs").extensions(&["md"]);
        let code = gen.generate_code(&tmp);

        assert!(code.contains("pub fn get_builtin_docs()"));
        assert!(code.contains(r#"("alpha""#));
        assert!(code.contains(r#"("beta""#));
        assert!(code.contains("# Alpha content"));
        assert!(code.contains("# Beta content"));
    }

    #[test]
    fn test_generate_code_filters_by_extension() {
        let tmp = tempdir();
        fs::write(tmp.join("included.md"), "yes").unwrap();
        fs::write(tmp.join("excluded.txt"), "no").unwrap();

        let gen = BuiltinGenerator::new("docs").extensions(&["md"]);
        let code = gen.generate_code(&tmp);

        assert!(code.contains(r#"("included""#));
        assert!(!code.contains("excluded"));
    }

    #[test]
    fn test_generate_code_recursive_subdirectories() {
        let tmp = tempdir();
        let sub = tmp.join("subdir");
        fs::create_dir(&sub).unwrap();
        fs::write(sub.join("nested.md"), "nested content").unwrap();

        let gen = BuiltinGenerator::new("docs").extensions(&["md"]);
        let code = gen.generate_code(&tmp);

        assert!(code.contains(r#"("subdir/nested""#));
        assert!(code.contains("nested content"));
    }

    #[test]
    fn test_generate_code_skip_dirs() {
        let tmp = tempdir();
        let skipped = tmp.join("skip_me");
        fs::create_dir(&skipped).unwrap();
        fs::write(skipped.join("hidden.md"), "hidden").unwrap();
        fs::write(tmp.join("visible.md"), "visible").unwrap();

        let gen = BuiltinGenerator::new("docs")
            .extensions(&["md"])
            .skip_dirs(&["skip_me"]);
        let code = gen.generate_code(&tmp);

        assert!(code.contains(r#"("visible""#));
        assert!(!code.contains("hidden"));
    }

    #[test]
    fn test_generate_code_preserve_extensions() {
        let tmp = tempdir();
        fs::write(tmp.join("skill.md"), "content").unwrap();

        let gen = BuiltinGenerator::new("skills")
            .extensions(&["md"])
            .preserve_extensions();
        let code = gen.generate_code(&tmp);

        assert!(code.contains(r#"("skill.md""#));
    }

    #[test]
    fn test_generate_code_content_with_quotes() {
        let tmp = tempdir();
        fs::write(tmp.join("tricky.md"), "She said \"hello\"").unwrap();

        let gen = BuiltinGenerator::new("docs").extensions(&["md"]);
        let code = gen.generate_code(&tmp);

        // Should use raw string hashes to handle the embedded quotes
        assert!(code.contains("tricky"));
        assert!(code.contains("She said"));
    }

    #[test]
    fn test_generate_code_multiple_extensions() {
        let tmp = tempdir();
        fs::write(tmp.join("a.md"), "markdown").unwrap();
        fs::write(tmp.join("b.yaml"), "yaml content").unwrap();
        fs::write(tmp.join("c.txt"), "ignored").unwrap();

        let gen = BuiltinGenerator::new("mixed").extensions(&["md", "yaml"]);
        let code = gen.generate_code(&tmp);

        assert!(code.contains("markdown"));
        assert!(code.contains("yaml content"));
        assert!(!code.contains("ignored"));
    }

    #[test]
    fn test_generate_with_env_vars() {
        let tmp = tempdir();
        let out = tempdir();
        fs::write(tmp.join("test.md"), "content").unwrap();

        // Set required env vars
        env::set_var("CARGO_MANIFEST_DIR", tmp.to_str().unwrap());
        env::set_var("OUT_DIR", out.to_str().unwrap());

        let gen = BuiltinGenerator::new("test")
            .source_dir(".")
            .output_name("builtin_test");
        gen.generate();

        let generated = out.join("builtin_test.rs");
        assert!(generated.exists());
        let code = fs::read_to_string(generated).unwrap();
        assert!(code.contains("pub fn get_builtin_test()"));
        assert!(code.contains("content"));
    }

    #[test]
    fn test_manifest_dir() {
        let tmp = tempdir();
        env::set_var("CARGO_MANIFEST_DIR", tmp.to_str().unwrap());
        assert_eq!(manifest_dir(), tmp);
    }

    #[test]
    fn test_out_dir() {
        let tmp = tempdir();
        env::set_var("OUT_DIR", tmp.to_str().unwrap());
        assert_eq!(out_dir(), tmp);
    }

    #[test]
    fn test_generate_code_deeply_nested() {
        let tmp = tempdir();
        let deep = tmp.join("a").join("b");
        fs::create_dir_all(&deep).unwrap();
        fs::write(deep.join("deep.md"), "deep").unwrap();

        let gen = BuiltinGenerator::new("docs").extensions(&["md"]);
        let code = gen.generate_code(&tmp);

        assert!(code.contains(r#"("a/b/deep""#));
    }

    #[test]
    fn test_collect_files_unreadable_dir_graceful() {
        // collect_files with a non-existent path just returns without error
        let gen = BuiltinGenerator::new("docs");
        let mut code = String::new();
        gen.collect_files(Path::new("/no/such/path"), "", &mut code);
        assert!(code.is_empty());
    }

    #[test]
    fn test_generate_code_header_comments() {
        let gen = BuiltinGenerator::new("widgets");
        let code = gen.generate_code(Path::new("/nonexistent"));

        assert!(code.contains("Auto-generated builtin widgets"));
        assert!(code.contains("Generated by build.rs"));
    }

    #[test]
    fn test_raw_string_hashes_quote_at_end() {
        // Quote at the very end of string — no chars after to count
        assert_eq!(raw_string_hashes("end\""), "#");
    }

    /// Helper: create a temporary directory that auto-cleans on drop.
    fn tempdir() -> PathBuf {
        let dir = env::temp_dir().join(format!(
            "swissarmyhammer-build-test-{}",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        fs::create_dir_all(&dir).unwrap();
        dir
    }
}
