[package]
name = "swissarmyhammer-workflow"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Workflow system for SwissArmyHammer - state-based execution engine with Mermaid support"

[dependencies]
# Core dependencies from workspace
tokio = { workspace = true }
tokio-util = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }

# Additional dependencies needed by workflow module
liquid = { workspace = true }
liquid-core = { workspace = true }
walkdir = { workspace = true }
dashmap = { workspace = true }
regex = { workspace = true }
ulid = { workspace = true }
chrono = { workspace = true }
chumsky = "0.9"
base64 = "0.22"

# SwissArmyHammer domain crates
swissarmyhammer-common = { path = "../swissarmyhammer-common" }
swissarmyhammer-templating = { path = "../swissarmyhammer-templating" }
swissarmyhammer-config = { path = "../swissarmyhammer-config" }
swissarmyhammer-shell = { path = "../swissarmyhammer-shell" }
swissarmyhammer = { path = "../swissarmyhammer" }

# Additional dependencies needed by workflow actions
syntect = { workspace = true }
dirs = { workspace = true }
axum = { workspace = true }
llama-agent = { workspace = true }
reqwest = { workspace = true }
# Additional dependencies not in workspace
which = "2.0"
zstd = "0.13"
mermaid-parser = { git = "https://github.com/wballard/mermaid_parser" }
cel-interpreter = "0.8"

[dev-dependencies]
# Test dependencies
tempfile = { workspace = true }
serial_test = { workspace = true }