// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {highlighting} from "./highlight"
const spec_word = {__proto__:null,not:14, NOT:16, and:24, AND:26, or:34, OR:36}
export const parser = LRParser.deserialize({
  version: 14,
  states: "#lOVQPOOOOQO'#Cu'#CuOOQO'#Cv'#CvOVQPO'#CaO!SQPO'#CpOVQPO'#CoOOQO'#Ct'#CtQVQPOOOOQO,58{,58{OOQO'#Cx'#CxOOQO'#Cf'#CfOVQPO,59POOQO'#Cy'#CyOOQO'#Ck'#CkOVQPO,59UO!pQPO,59ZOOQO-E6n-E6nOOQO1G.k1G.kO!wQPO1G.pOOQO1G.u1G.u",
  stateData: "$Q~OgOS~OQPORPOSPOUROVQOWQOoTO~OZYO[XO]XO`]Oa[Ob[O~OQdXRdXSdXUdXVdXWdXedXodX~PnOncO~PnOZYO[XO]XOQ^iR^iS^iU^iV^iW^i`^ia^ib^ie^io^in^i~OQRSZ`kZ~",
  goto: "!ynPPPPPoPPPowPPPo|PPPo!QPPP!Wo!hP!p!u]UORTVZ^VZS_bT^S_QVOR`VSSOVQWRQ_TQaZRb^]RORTVZ^VYS_bT]S_",
  nodeNames: "⚠ FilterExpr Tag Mention Ref Not Bang not not And AndOp AmpAmp and and Or OrOp PipePipe or or Group",
  maxTerm: 31,
  propSources: [highlighting],
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "&[~R^XY}YZ}]^}pq}qr!`st!evw#cxy#nyz#s!b!c#x!c!}$v#Q#R%R#T#o$v#p#q&P~!SSg~XY}YZ}]^}pq}~!eOU~~!hU}!O!z!O!P!z!Q![!z!c!}!z#R#S!z#T#o!z~#PUQ~}!O!z!O!P!z!Q![!z!c!}!z#R#S!z#T#o!z~#fPvw#i~#nOZ~~#sOo~~#xOn~~#{U}!O$_!O!P$_!Q![$_!c!}$_#R#S$_#T#o$_~$dUR~}!O$_!O!P$_!Q![$_!c!}$_#R#S$_#T#o$_~${Qk~!c!}$v#T#o$v~%UU}!O%h!O!P%h!Q![%h!c!}%h#R#S%h#T#o%h~%mUS~}!O%h!O!P%h!Q![%h!c!}%h#R#S%h#T#o%h~&SP#p#q&V~&[O`~",
  tokenizers: [0],
  topRules: {"FilterExpr":[0,1]},
  specialized: [{term: 27, get: (value) => spec_word[value] || -1}],
  tokenPrec: 132
})
