// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  FilterExpr = 1,
  Tag = 2,
  Mention = 3,
  Ref = 4,
  Not = 5,
  Bang = 6,
  not = 8,
  And = 9,
  AndOp = 10,
  AmpAmp = 11,
  and = 13,
  Or = 14,
  OrOp = 15,
  PipePipe = 16,
  or = 18,
  Group = 19
