// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {highlighting} from "./highlight"
const spec_word = {__proto__:null,not:16, NOT:18, and:26, AND:28, or:36, OR:38}
export const parser = LRParser.deserialize({
  version: 14,
  states: "#lOVQPOOOOQO'#Cv'#CvOOQO'#Cw'#CwOVQPO'#CbO!VQPO'#CqOVQPO'#CpOOQO'#Cu'#CuQVQPOOOOQO,58|,58|OOQO'#Cy'#CyOOQO'#Cg'#CgOVQPO,59QOOQO'#Cz'#CzOOQO'#Cl'#ClOVQPO,59VO!vQPO,59[OOQO-E6o-E6oOOQO1G.l1G.lO!}QPO1G.qOOQO1G.v1G.v",
  stateData: "$[~OhOS~OQPORPOSPOTPOVROWQOXQOpTO~O[YO]XO^XOa]Ob[Oc[O~OQeXReXSeXTeXVeXWeXXeXfeXpeX~PqOocO~PqO[YO]XO^XOQ_iR_iS_iT_iV_iW_iX_ia_ib_ic_if_ip_io_i~OQRST[alT~",
  goto: "!zoPPPPPPpPPPpxPPPp}PPPp!RPPP!Xp!iP!q!v]UORTVZ^VZS_bT^S_QVOR`VSSOVQWRQ_TQaZRb^]RORTVZ^VYS_bT]S_",
  nodeNames: "⚠ FilterExpr Tag Mention Ref Project Not Bang not not And AndOp AmpAmp and and Or OrOp PipePipe or or Group",
  maxTerm: 32,
  propSources: [highlighting],
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "']~R_XY!QYZ!Q]^!Qpq!Qqr!cst!htu#fvw$dxy$oyz$t!b!c$y!c!}%w#Q#R&S#T#o%w#p#q'Q~!VSh~XY!QYZ!Q]^!Qpq!Q~!hOV~~!kU}!O!}!O!P!}!Q![!}!c!}!}#R#S!}#T#o!}~#SUQ~}!O!}!O!P!}!Q![!}!c!}!}#R#S!}#T#o!}~#iU}!O#{!O!P#{!Q![#{!c!}#{#R#S#{#T#o#{~$QUT~}!O#{!O!P#{!Q![#{!c!}#{#R#S#{#T#o#{~$gPvw$j~$oO[~~$tOp~~$yOo~~$|U}!O%`!O!P%`!Q![%`!c!}%`#R#S%`#T#o%`~%eUR~}!O%`!O!P%`!Q![%`!c!}%`#R#S%`#T#o%`~%|Ql~!c!}%w#T#o%w~&VU}!O&i!O!P&i!Q![&i!c!}&i#R#S&i#T#o&i~&nUS~}!O&i!O!P&i!Q![&i!c!}&i#R#S&i#T#o&i~'TP#p#q'W~']Oa~",
  tokenizers: [0],
  topRules: {"FilterExpr":[0,1]},
  specialized: [{term: 28, get: (value) => spec_word[value] || -1}],
  tokenPrec: 141
})
